### ISSUE TITLE
Implement STARTTLS for circuits.net.sockets

### ISSUE THREAD

**Issue by prologic** [circuits/circuits#113]
Maybe we can leverage this [Tornado STARTTLS example](https://gist.github.com/weaver/293449).

I'd like to see an API such as this:

``` #!python
"""Simple TLS Echo Server"""


from circuits import Component
from circuits.net.tls import starttls, TLS
from circuits.net.sockets import TCPServer


class TLSEchoServer(Component):

    def init(self, bind):
        self.transport = (TCPServer(*bind) + TLS()).register(self)

    def read(self, sock, data):
        if data.strip.upper() == "STARTTLS":
            return self.fire(starttls())
        return data


TLSEchoServer(("0.0.0.0", 8000)).run()
```

Thoughts?

**Comment by spaceone** [comment]
The goal of this issue is to SSL-wrap the socket afterwards? So that it can speak both either plaintext or TLS/SSL depending on if the endpoint initiates it?

**Comment by prologic** [comment]
As in the example the goal here is to provide mechanisms for the developer to easily build TLS features into their application or protocol. So yes :)

**Comment by spaceone** [comment]
I implemented a example implementation for Upgrading a HTTP connection to TLS in `circuits.http` using this new feature: https://github.com/spaceone/circuits.http/commit/ab626c851b1472b119c8f3c0491451703e3507a4

**Comment by prologic** [comment]
Can you add such an examples to examples/ as well (if possible)?


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by spaceone** [comment]
The commit message contains one which could be used for this.

**Comment by spaceone** [comment]
I will do this somewhen and I will also add a test case.

**Comment by prologic** [comment]
Perfect :)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au
