### ISSUE TITLE
Incorporate setuptools_scm for versioning

### ISSUE THREAD

**Issue by prologic** [circuits/circuits#116]
Let's incorporate [setuptools_scm](https://pypi.python.org/pypi/setuptools_scm) into circuits for packaging and distribution so we no longer have to "manually" manage the version. I've had good success with this tool for a few other projects recently.

**Comment by spaceone** [comment]
This broke circuits. You removed version.py which is imported in `__init__.py`.

**Comment by prologic** [comment]
It shouldn't and obviously it works as I'm using circuits in production in quite a few places at it's ``HEAD`` revision. [setuptools_scm](https://pypi.python.org/pypi/setuptools_scm) actually automatically generates a ``circuits/version.py`` modules; so the import *should* work :)

**Comment by spaceone** [comment]
hmm. I am working with the git checkout of circuits. I don't call setup.py.

**Comment by prologic** [comment]
You have to *at least* ``pip install -e .`` Do you not use pip or setup.py normally?

**Comment by spaceone** [comment]
Never.

**Comment by prologic** [comment]
So you just call ``add2virtualenv``?

**Comment by spaceone** [comment]
I don't work with virtual environments.

**Comment by prologic** [comment]
Hmm I'm not sure what to do here if you don't at least run the ``setup.py``

**Comment by spaceone** [comment]
Adding a fallback version.py? Or add a try-except around that import?
