### ISSUE TITLE
Help with Logo

### ISSUE THREAD

**Issue by elioqoshi** [circuits/circuits#129]
Hola!
I saw your job announcement on Open Source Design and would love to help with a new logo if you are still interested.
You can find my stuff on http://elioqoshi.me if you want to have a look :)

Cheers!

**Comment by prologic** [comment]
@elioqoshi Hi (*Hola!*)! Yes that would be fantastic! How shall we proceed?

**Comment by elioqoshi** [comment]
Hey again,
So I guess you don't have a budget for this, right? I'd be okay to do this for free in that case. :)
 I will come up with some draft ideas and post them here.

**Comment by prologic** [comment]
Yeah no I don't have a budget; sorry :) I continue to support this project in my "spare time" which inevitably seems to keep my mind sharp for my real job :) -- So Thank you!

**Comment by elioqoshi** [comment]
Here is the first proposal. I used an open source font of course :)
What do you think?

![1](https://cloud.githubusercontent.com/assets/5436686/9846440/6ea828e8-5ad2-11e5-981c-6489244807a5.jpg)

**Comment by prologic** [comment]
Haha this already looks way better! Thank you. I assume you've read a little about the project? The overarching idea being that you write complex software from the composition of smaller components; ala "circuits" not to dissimilar to how you'd pick and place electronic components on a breadboard :) -- What you've already come up with is well awesome! (*I have no UI/Design skills :P*)

**Comment by elioqoshi** [comment]
Sure I did! :)
I think this is something we can go with. I will pause and see if I can get some other inspirations, but this is quite solid, I'd humbly say :)

**Comment by prologic** [comment]
Yeah no I completely agree! So if nothing else "springs to mind" :) Let's run with this and if you perhaps commit a pull request on circuits it'll have your name all over it; I'll make sure to stick your name and website on the website too.

**Comment by elioqoshi** [comment]
Thanks, appreciate it! Will get you the logo in all needed formats by tomorrow :)

**Comment by prologic** [comment]
Fantastic! Thank you so much! Your work is pretty awesome!

**Comment by spaceone** [comment]
Nice. You could attach a SVG and PNG as well.

**Comment by elioqoshi** [comment]
Here we go! Let  me know if you need help with conversions or similar
https://dl.dropboxusercontent.com/u/62482708/Circuits/Circuit%20Logo.zip

**Comment by prologic** [comment]
@elioqoshi Thank you so much for these! I'll commit these to https://github.com/circuits/circuits shortly -- Watch out for a PR that I'll CC you in on for the website updates/etc :)

**Comment by prologic** [comment]
Tasks:

- [ ] Commit assets to circuits repository (*attribute @elioqoshi*)
- [ ] Update documentation logo
- [ ] Update website logo/header
- [ ] Add a "Logo by @elioqoshi" and links to the website footer

**Comment by elioqoshi** [comment]
My pleasure @prologic and thank you!

**Comment by nathschmidt** [comment]
@elioqoshi Love the new logo! Looks great.

You mentioned you went with an open font, which one did you choose?

**Comment by elioqoshi** [comment]
Thank you @nathschmidt !

I went with Exo here.
http://www.fontsquirrel.com/fonts/exo

It's licensed under a SIL Open Font License :)

**Comment by prologic** [comment]
This is done. We've incorporated this :) Thank you @elioqoshi
