### ISSUE TITLE
Rebuild a new statically generated website

### ISSUE THREAD

**Issue by prologic** [circuits/circuits#13]
See #7

**Comment by spaceone** [comment]
What's the goal here? A more modern design? Or content related?

**Comment by spaceone** [comment]
Usabiliy improovements would be good. The surfer of the page should have immediately the feeling that he want to use circuits.
The examples should be more in the top, and there should be better examples.

**Comment by spaceone** [comment]
Nobody cares about tweets IMHO.

**Comment by spaceone** [comment]
There is too much introduction text (important for first impression).

**Comment by prologic** [comment]
Yeap all agree :)

* Modern Design
* Better attracting headlines and content, examples, etc

**Comment by prologic** [comment]
Thinking abut using [staticco](https://github.com/oss6/statico) here and going ot have a read of [Automate GitHub Pages Deploys](http://ablog.readthedocs.org/manual/auto-github-pages-deploys/)

**Comment by prologic** [comment]
See also (*upcoming demo/example site*): oss6/statico#2

**Comment by prologic** [comment]
Do we know anything in the community that's a good frontend designer to help us out here?

**Comment by prologic** [comment]
WIP: https://circuits.github.io/

See: https://github.com/circuits/circuits.github.io

**Comment by spaceone** [comment]
looks very very nice!

**Comment by prologic** [comment]
Hahaha I don't think it's that great :P my design skills aren't that crash hot! But thanks :) Feel free to contribute!

**Comment by prologic** [comment]
So what other changes do we want to make here?

Right now I'm duplicating a lot of the old content into this new structure/form.

**Comment by prologic** [comment]
Updates:

* Added Community page
* Added Projects using circuits page
* Added a README
* Added a CONTRIBUTING guide

**Comment by prologic** [comment]
Update:

* Added first news post (*unfinished*).

Need more ideas; start throwing em around guys!

**Comment by prologic** [comment]
I think I'm done rebuilding the website statically using Pelican and making it look a lot more modern. Unless there's something more to do here I think we should resolve this issue and raise future isseus regarding the website on https://github.com/circuits/circuits.github.io/issues

**Comment by prologic** [comment]
New [circuits website](https://circuitsframework.com) is now considered complete. DNS updated and repoitned.

**Comment by prologic** [comment]
**Note:** DNS redelegation might take a while.

**Comment by spaceone** [comment]
It shows 404 - There isn't a GitHub Pages site here.

**Comment by prologic** [comment]
Yeah you were too quick like I was :) Give it time for the DNS to update!

**Comment by spaceone** [comment]
hm, but DNS points already to github. Or does github need to do something?

**Comment by prologic** [comment]
Should just work off the contents of the CNAME file Hmm

**Comment by prologic** [comment]
Hopefully this is fixed; I think it was because I forgot to configure Pelican for some static paths to copy.

**Comment by spaceone** [comment]
Still 404.

**Comment by prologic** [comment]
According to https://help.github.com/articles/tips-for-configuring-an-a-record-with-your-dns-provider/ I had configured the DNS wrong. Hopefully I've fixed it :) TTL is 1800s

**Comment by spaceone** [comment]
yes, works now

**Comment by prologic** [comment]
Oh geez that was quick for you  :P My local dns i still caching the old records :/

**Comment by spaceone** [comment]
execute "nscd -i hosts" as root.

**Comment by prologic** [comment]
Didn't do squats :)
