### ISSUE TITLE
WebSocketCodec should fire a connect

### ISSUE THREAD

**Issue by mnlipp** [circuits/circuits#131]
WebSocketCodec should fire a "connect(self.\_sock)" event in its \_\_init\_\_ before it fires the first "read".

While it is, of course, possible to deduce a new connection from the "read" events by checking for new sockets, it is quite tedious. And as we get a "close" event, it would only be reasonable and "symmetrical" to also get the corresponding "connect" event.

**Comment by mnlipp** [comment]
To be precise, the "connect" must be fired before checking for messages, to make sure that it is fired even if the client connects without initially sending a message.

My use case is that the client connects, and in response to this connection immediately gets some data pushed to the client. So the message exchange is actually initiated by the server. As there is no "connect" event, the component that sends the initial message to the client needs a component relationship to the WebSocketsDispatcher.

**Comment by mnlipp** [comment]
Okay, it *is* generated. Found it.

**Comment by prologic** [comment]
LOL Did you just have a mailing list conversation with yourself?

Anything else you need help with ? :)

cheers
James


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by mnlipp** [comment]
Well, yes. It's been some time that I used circuits and it takes some 
time to get used to using it again. You introduced some nasty changes 
(meaning incompatibilities). That's okay in a major version change, of 
course. But some hints in the Changelog would have been nice (e.g. 
addHandler now adding the component as "self" if you add a function -- 
not to speak of all event classes using lower case now).

It's hard to keep track of all the event consumption and generation of a 
component. Maybe we'd need some kind of clever graphical representation 
for the behaviour of the components. Maybe UML activity diagrams with 
senders/receivers would do. I'll have to think about it.

;-)

     Michael


Am 01.10.2015 um 18:16 schrieb James Mills:
> LOL Did you just have a mailing list conversation with yourself?
>
> Anything else you need help with ? :)
>
> cheers
> James
>
>
> James Mills / prologic
>
> E: prologic@shortcircuit.net.au
> W: prologic.shortcircuit.net.au
>

**Comment by prologic** [comment]
All very good points; very sorry about the unclear documentation and
communication on some of those breaking changes. I am quite positive we did
document this change
somewhere but the fact that I can't find it is terrible! So sorry!

One thing I'm trying to do going forward is two things:

a) Release more regularly
b) Document things a lot better

cheers
James


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au
