### ISSUE TITLE
circuits.web.Sessions should have an expire method

### ISSUE THREAD

**Issue by mnlipp** [circuits/circuits#133]
The policy, when to expire a session, is, of course, application dependent. But `Sessions` should have a method `expire(session)` that removes the session from the dict. Currently, you have to access the Sessions object's _data attribute, which violates the python conventions.

As an alternative, the class' comment could point out that sessions don't expire and encourage users to develop and use session managers derived from `Sessions` that implement a policy for expiration (and can access _data "legally", depending on whether you consider an _attribute in python private or protected). Of course, from a designer's point of view, it would still be better to provide a method.

**Comment by prologic** [comment]
Seems like adding .expire() would be a good idea :)

Solidifying a base class and API for all derived session management would
be good :)

Let's add this as a new issue; seems it would be trivial to add this?

cheers
James


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by eriol** [comment]
@mnlipp you were talking about something like this https://github.com/circuits/circuits/commit/a0bdf7e253bf6f34baba7aa47c5407b68143d3bd? Only exposing a method to not use `_data` directly, or something more/different?

**Comment by mnlipp** [comment]
Yes, this is all I meant to address.
