### ISSUE TITLE
Dispatcher "Static" doesn't accept channel keyword parameter

### ISSUE THREAD

**Issue by mnlipp** [circuits/circuits#134]
Well, subject says it. `circuits.web.dispatchers.Static` doesn't follow the usual pattern of passing kwargs to its base class. So you cannot create `Static(channel="ui")`.

Workaround is 
```python
static=Static()
static.channel = "ui"
```
but it's annoying.

**Comment by prologic** [comment]
Yeah valid point! Let's fix this ASAP :)
