### ISSUE TITLE
circuits.web can handle only one cookie

### ISSUE THREAD

**Issue by mnlipp** [circuits/circuits#135]
In circuits.web.wrappers.Response.prepare cookies are handles this way:
```python
        for k, v in self.cookie.items():
            self.headers.add_header("Set-Cookie", v.OutputString())
```

Problem is that `self.headers` is basically a `dict`. Setting a second value with the same key appends that value to the existing value separated with a comma. While this work for most headers, it doesn't work for Set-Cookie. This header may (and must) appear several times in a response if you want to set multiple cookies.

I'm not sure how to handle this. Maybe the convention could be to allow lists as values in `self.headers`. When converting the headers to text in circuits.web.http.HTTP.on_response, such entries would be converted to several headers with the same key.

**Comment by spaceone** [comment]
```
   Origin servers SHOULD NOT fold multiple Set-Cookie header fields into
   a single header field.  The usual mechanism for folding HTTP headers
   fields (i.e., as defined in [RFC2616]) might change the semantics of
   the Set-Cookie header field because the %x2C (",") character is used
   by Set-Cookie in a way that conflicts with such folding.
```
http://tools.ietf.org/html/rfc6265

→ It's not a MUST, it's a SHOULD

**Comment by prologic** [comment]
Remember that a lot of this code was in fact borrowed from other sources :)

So should we *fix* this? One Set-Cookie header per cookie?

cheers
James


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by mnlipp** [comment]
We should definitely fix this. Because although it is a SHOULD, it simply doesn't work. I tested it with both chrome and firefox. Neither splits the cookie at the comma. I end up with a single cookie in my browser(s) that has a value containing commas. Now, I might send bug reports to Google and Mozilla, but that wouldn't get me anywhere, right?

However, as commas are illegal in cookie values, this is easier to fix in circuits than I thought. Below is the patch against 3.1 (sorry, currently not time to set up the fork/pull stuff for such a small change).

```
diff --git a/circuits/web/headers.py b/circuits/web/headers.py
index 8b426c2..ed6c34c 100644
--- a/circuits/web/headers.py
+++ b/circuits/web/headers.py
@@ -214,7 +214,12 @@
         return "Headers(%s)" % repr(list(self.items()))
 
     def __str__(self):
-        headers = ["%s: %s\r\n" % (k, v) for k, v in self.items()]
+        headers = ["%s: %s\r\n" % (k, v) \
+                   for k, v in self.items() if k.lower() != "set-cookie" ]
+        cookies = self.get("set-cookie")
+        if cookies:
+            headers.extend(["Set-Cookie: %s\r\n" % v \
+                            for v in cookies.split(",")])
         return "".join(headers) + '\r\n'
 
     def __bytes__(self):
```

**Comment by spaceone** [comment]
You can't use cookies.split(',') because the expires-date contains a ','.

**Comment by spaceone** [comment]
The value might also contain a ','.

**Comment by mnlipp** [comment]
Right, I only looked at the syntax of the cookie-value (which may definitely not contain a ','
```
cookie-value      = *cookie-octet / ( DQUOTE *cookie-octet DQUOTE )
cookie-octet      = %x21 / %x23-2B / %x2D-3A / %x3C-5B / %x5D-7E
                       ; US-ASCII characters excluding CTLs,
                       ; whitespace DQUOTE, comma, semicolon,
                       ; and backslash
```
), forgot about the cookie-av(s).

Well, looks like we need lists as values in the Header after all. If nobody comes up with a better idea, I'll fix it with a list as value for that special header key.

BTW I think the problem with the RFC is that the parsing algorithm described for the user agent doesn't handle the comma. So if you adhere to the algorithm in your user agent's implementation, comma separated Set-Cookie headers aren't handled as the sever may have intended.

**Comment by spaceone** [comment]
You could steal the logic of _CookieElement+SetCookie in https://github.com/spaceone/httoop / https://github.com/spaceone/circuits.http plus your workaround:
```
headers.extend('Set-Cookie: %s' % (bytes(cookie),) for cookie in headers.elements('Set-Cookie'))
```
This would still store it internally with a ', ' but is correctly split into multiple header fields.

**Comment by mnlipp** [comment]
Maybe I could. But what would be the advantage of first concatenating something into a string only to split it up with some (non trivial) parsing algorithm later?

**Comment by mnlipp** [comment]
Okay, this problem just became CRITICAL as I found that Chrome adds its own cookies (gsScollPos) and my app's session cookie got screwed up.

So here's the better patch:

```
diff --git a/circuits/web/headers.py b/circuits/web/headers.py
index 8b426c2..96363b8 100644
--- a/circuits/web/headers.py
+++ b/circuits/web/headers.py
@@ -202,19 +202,31 @@
 
 class Headers(CaseInsensitiveDict):
 
+    def __init__(self, *args, **kwargs):
+        super(Headers, self).__init__(*args, **kwargs)
+        self["Set-Cookie"] = []
+        
     def elements(self, key):
         """Return a sorted list of HeaderElements for the given header."""
         return header_elements(key, self.get(key))
 
     def get_all(self, name):
         """Return a list of all the values for the named field."""
-        return [val.strip() for val in self.get(name, '').split(',')]
+        value = self.get(name, '')
+        if isinstance(value, list):
+            return value
+        return [val.strip() for val in value.split(',')]
 
     def __repr__(self):
         return "Headers(%s)" % repr(list(self.items()))
 
     def __str__(self):
-        headers = ["%s: %s\r\n" % (k, v) for k, v in self.items()]
+        headers = []
+        for k, v in self.items():
+            if not isinstance(v, list):
+                headers.append("%s: %s\r\n" % (k, v))
+            else:
+                headers.extend(["%s: %s\r\n" % (k, vv) for vv in v ])
         return "".join(headers) + '\r\n'
 
     def __bytes__(self):
@@ -224,7 +236,10 @@
         if not key in self:
             self[key] = value
         else:
-            self[key] = ", ".join([self[key], value])
+            if isinstance(self[key], list):
+                self[key].append(value)
+            else:
+                self[key] = ", ".join([self[key], value])
 
     def add_header(self, _name, _value, **_params):
         """Extended header setting.
```

**Comment by prologic** [comment]
Pull Request? :) Let's get this in!

**Comment by spaceone** [comment]
```
      Note: In practice, the "Set-Cookie" header field ([RFC6265]) often
      appears multiple times in a response message and does not use the
      list syntax, violating the above requirements on multiple header
      fields with the same name.  Since it cannot be combined into a
      single field-value, recipients ought to handle "Set-Cookie" as a
      special case while processing header fields.
```
RFC 7230

**Comment by spaceone** [comment]
Thank you. I squashed the commits and fixed the whitespace errors. All tests are passing. If you write a test script for this it would be nice.

**Comment by prologic** [comment]
:+1: awesome stuff guys :)
