### ISSUE TITLE
HTTP 304 response has body

### ISSUE THREAD

**Issue by mnlipp** [circuits/circuits#138]
The `redirect` event sets the body to None, as it should (web/errors.py:304)
```
            # "The 304 response MUST NOT contain a message-body."
            response.body = None
```

In web/http.py:364, however, this is "undone" because the `redirect` is an `httperror`, which semantically isn't really true.
```
        elif isinstance(value, httperror):
            res.body = str(value)
```

Simple way to fix: introduce a layer when deriving the classes httperror->httpmessage->Event
and redirect->httpmessage.

**Comment by prologic** [comment]
:+1:

**Comment by spaceone** [comment]
Don't introduce one more (API) type. Fixed by not returning anything in `__str__()` where it is forbidden. With httoop/circuits.http this would never have happened.

**Comment by prologic** [comment]
:+1: awesome work guys :)
