### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by pdurbin** [circuits/circuits#14]
For the same reasons as https://github.com/openhatch/oh-mainline/issues/1560

**Comment by prologic** [comment]
:+1:

**Comment by prologic** [comment]
@pdurbin Are you waiting for me to do this or am I waiting for a PR from you? :)

**Comment by pdurbin** [comment]
@prologic I think you should write it up since you'll know best how people can effectively contribute.

**Comment by prologic** [comment]
Okay :)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by prologic** [comment]
Came across [CONTRIBUTING.md](http://contribute.md/)

Going to use this as a template :)

**Comment by prologic** [comment]
@pdurbin @spaceone @y0no Any thoughts on this? Feedback? :)

**Comment by prologic** [comment]
See PR #71

**Comment by y0no** [comment]
I'm okay with that

**Comment by prologic** [comment]
:+1:
