### ISSUE TITLE
Drop Python 2.6/3.2

### ISSUE THREAD

**Issue by prologic** [circuits/circuits#152]
Should we drop Python 3.2?

AFAIK this was a broken version of Python where they removed Unicode literals `u"foo"` then added them back in again in 3.3? This obviously breaks a lot of things and CI tests for this version currently blow up before they even start because 3rd-party libraries can't cope:

https://travis-ci.org/circuits/circuits/jobs/103183932

**Comment by prologic** [comment]
@spaceone Thoughts?

**Comment by prologic** [comment]
For that matter should we also drop 2.6 while we're at it? AFAIK every major platform has upgraded to a 2.6 minimum and 2.6 AFAIK is also EOL (*End Of Life*).

**Comment by spaceone** [comment]
I don't think 3.2 is still used, while I think that 2.6 is still in use (at least 2 years ago I had some systems with it). How much workarounds do we have due to 2.6? How much projects did drop 2.6 support?

**Comment by prologic** [comment]
Two very good questions. In terms of work-arounds for continuing to support Python 2.6 i can think of:

- Non support for dict comprehensions
- Non support for unnumbered format specifiers. e.g: ``"{}{}".format91, 2)``
- Broken ssl support?

**Comment by eriol** [comment]
First many thanks @prologic to bring me to this team! :smile:
I will check on distribution side to have an overview on the situation. We can already exclude Debian for Python 2.6: it was supported by Squeeze (oldoldstable) for whitch LTS support ended at 2016-02-29.

**Comment by spaceone** [comment]
Nowerdays I think dropping python 2.6 is fine! I saw some projects doing this as well. e.g. pyca/tls.

**Comment by spaceone** [comment]
https://www.python.org/download/releases/2.6.9/

**Comment by prologic** [comment]
Shall  we rename this issue to "Drop Python 2.6/3.2" to reflect the conversation :)

I think if we do we should also remove any work-around code for these versions of CPython?

**Comment by prologic** [comment]
@eriol  You're most welcome :) We appreciate your continued efforts!

**Comment by eriol** [comment]
I did a bit of investigation: RHEL 6 has py2.6 and is supported till 2020[¹], but it has Python 3.4 available using Software Collections[²]. Gentoo supports only 2.7 and >=3.3[³]. Ubuntu has py3.2 in precise (the 12.04 LTS) but not support anymore py2.6. Arch switched to python3 years ago, I don't remember when, but it's a rolling release so I'm sure it will using py3.5 now.

So, also considering downstream support, I think it's safe to drop 2.6 and 3.2 in circuits 3.3.

I'm also +1 for removing work-around code for versions we not support.

[¹] https://access.redhat.com/support/policy/updates/errata#Life_Cycle_Dates
[²] https://www.softwarecollections.org/en/scls/rhscl/rh-python34/
[³] https://wiki.gentoo.org/wiki/Project:Python/Implementations

**Comment by prologic** [comment]
Nice work! I think it's settled then.

This Issue/Task should then be able dropping said CPython ersions
and removing any such work-around code.

cheers
James


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by spaceone** [comment]
I added a new branch https://github.com/circuits/circuits/tree/drop_python_support.
I commited the meta things accidently also to master (didn't see the milestone is 3.3). I could not force-push to the master branch - was prvevented by a hook. @prologic Can you remove the commit?

**Comment by hpyle** [comment]
Sorry I'm late to this issue - I just saw the commit.  We have customers using Python 2.6 in some RHEL and CentOS environments, so would like to keep active support for that in the main branch if possible.

**Comment by spaceone** [comment]
@hpyle Yes, sorry this was only an accident.

**Comment by hpyle** [comment]
Thanks @spaceone.  Ping me by email if you want to discuss in more detail.

**Comment by eriol** [comment]
@hpyle thanks for sharing your concerns.
Do you think you will be able to switch to Python 2.7 using Software Collections[¹], for circuits **3.3**, or you would like to have more time? Consider that AFAIK there is no ETA yet for circuits 3.3.

[¹] https://www.softwarecollections.org/en/scls/rhscl/python27/

**Comment by hpyle** [comment]
The main use cases are stuck in Docker containers that will be hard to upgrade beyond python 2.6, at least in the short term.  But as long as this change goes into a numbered release of Circuits, we will be able to fix dependencies at the earlier version.

**Comment by apollo13** [comment]
I'll happily prepare a PR to drop 2.6/3.2 after #188 and #189 are merged.

Things (from a first glance) to do:
 * Update version specifiers in setup.py
 * Update tox.ini
 * Update .travis.yml
 * remove any 2.6 specific code (version checks mostly probably)

**Comment by apollo13** [comment]
Master is now py2.7 only in preparation for 3.3, please use circuits 3.2 for 2.6 support.
