### ISSUE TITLE
Release schedule?

### ISSUE THREAD

**Issue by keli** [circuits/circuits#158]
Hi, 

I've noticed that there hasn't been a release for more than a year and half. I really think commit 6d91594 needs to be released, sooner than later, because the bug is messing up any third-party library that imports from `six.moves`, and potential users might walk away because of that.

Thanks,
Keli

**Comment by prologic** [comment]
Sure :)

**Comment by spaceone** [comment]
could we just add a minor release?

**Comment by spaceone** [comment]
like immediately.

**Comment by prologic** [comment]
@spaceone Yeah that's what we're gonna do I think. There are no breaking changes (we've only done that 3 times :P) -- Do you want to do a sprint with me say on a weekend or something? I'll try a cut a release in the menatime.

**Comment by prologic** [comment]
Err sorry @spaceone I meant that for @justingiorgi since we're both in the Bay Area :)

**Comment by prologic** [comment]
In fact are there any other circuits devs/users in the Bay Area?

**Comment by justingiorgi** [comment]
I'd be up for a weekend sprint :)

**Comment by prologic** [comment]
Done: [circuits-3.2](https://pypi.python.org/pypi/circuits/3.2)
