### ISSUE TITLE
NameError when packaged with Py2Exe

### ISSUE THREAD

**Issue by prologic** [circuits/circuits#171]
A `NameError` is thrown when running a circuits app packaged with Py2Exe. Regression in circuits 3.2

**Comment by prologic** [comment]
@AdricEpic Is this right? (*creating issue for tracking, changelog and release notes*)

**Comment by AdricEpic** [comment]
Yes, that's correct. My py2exe settings include `{'compressed': True, 'bundle_files': 1}`, and I haven't tested other configs to see if it's just the zip-bundled version that the issue occurs in.

**Comment by prologic** [comment]
Can you see if this occurs with zip_safe=True and a zipped package (without
Py2Exe in the picture)?


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by AdricEpic** [comment]
Using the unmodified __init__, my app works when packaged as a .egg using zip_safe=True. I'm not terribly familiar with packaging non-EXE distributions, so please let me know if you meant something other than a .egg.

**Comment by prologic** [comment]
Ahh I was just curious :)

Okay let's get this merged in for 3.2.1

I want to release 3.2.1 shortly so hopefully no-one has found any other
significant issues or I want to hear about them ASAP :)

cheers
James


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au
