### ISSUE TITLE
Make tests pass also on Mac OS

### ISSUE THREAD

**Issue by eriol** [circuits/circuits#174]
According Travis history we are experiencing continuous builds failure since 10 months. It is not really the case since I was able to run the testsuite on my laptop (using Debian Stretch) without failing tests for CPython 2.7, 3.5 and PyPy.
Sometimes there are 1 or 2 tests failing so we should just identify those and make them reliable.

I would happy to have this issue as a release goal for circuits 3.3, if it seems feasible.

**Comment by prologic** [comment]
This is awesome! Thanks :) Let's definitely focus on this for 3.3

**Comment by spaceone** [comment]
Travis says that all tests are passing but not on a MAC and not the pyton2.6 tests.

**Comment by spaceone** [comment]
https://travis-ci.org/circuits/circuits/builds/143689275

**Comment by eriol** [comment]
@spaceone unfortunately not always: https://travis-ci.org/circuits/circuits/builds/142677985

I got some errors running tox locally, as I explained earlier on Debian Stretch. I did not enabled tests in the official Debian package because a failing test during build is an RC bug that lead to the autoremoval of a package.

But tests seems to fail randomly.

Anyway if macOS is a supported platform I think we should make the testsuite works also there: I will not be able to help on this since I did not have any machines with macOS.

**Comment by prologic** [comment]
@eriol OS X and conversely *BSD has come up as a "wanted" and "supported" platform several times. I myself am primarily developing on OS X these days too. So we'll get a stable test suite passing on Travis CI's Mac infrastructure for sure :)

**Comment by spaceone** [comment]
MacOS: me neither…
@eriol The link you posted actually failed due to a broken commit - The tests ran without https://github.com/circuits/circuits/commit/0b2f624b45cdf642a27f040aac02ccfb3f84a740

**Comment by eriol** [comment]
Ouch, sorry for the noise then. I experienced yesterday on my dev machine after enabling py35, so after 0b2f624, but now I did run 3 times the testsuite and it's working. Maybe we can leave the title of this bug for a few days and then change to something like "Make tests pass on macOS". Or close the bug...

Sorry again!

**Comment by prologic** [comment]
Working on fixing OS X tests...

**Comment by eriol** [comment]
I renamed the issue so it reflects what it's really about.

**Comment by prologic** [comment]
Thanks!


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au
