### ISSUE TITLE
circuits mini hackathon #1

### ISSUE THREAD

**Issue by prologic** [circuits/circuits#175]
TL;DR: mini-Hackathon this weekend (PDT).
----

Let's try something new :) Let's have a mini-Hackathon this weekend 22nd July 2016 to 23rd July 2016. Let's know over some outstanding issues and push a few releases out!

Let's host this on #circuits on FreeNode (`/server irc.freenode.net`) and have fun!

A few of us will be hacking in person in the Bay Area, SF for the rest of you we'll be on IRC too!

**Comment by spaceone** [comment]
I'm not here this weekend. And the next 3 weeks I'm on holidays :/

**Comment by justingiorgi** [comment]
I'm there! It's been a long time since I got to hack on Circuits.

**Comment by eriol** [comment]
I hope to be able to join tomorrow! Sorry for the late reply.

**Comment by prologic** [comment]
Awesome! On IRC I assume? Look forward to it :)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by eriol** [comment]
@prologic Yes, on IRC since I'm too far away: I live in Sicily, so CEST timezone.
Sorry, I did not think it was better to specify it! :smile:

**Comment by prologic** [comment]
No worries! :) See you online then!


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by prologic** [comment]
So this happened! The event went well enough for my first time hosting such a thing. Thanks to the following who contributed and/or physically attended:

- @eriol 
- @justingiorgi 
-  @cvshumake

We didn't end up getting much done; but it was fun nonetheless. We worked on:

- Improving the test suite on OS X / BSD
- Adding support for expiring sessions in circuits.web
- ideas for a Go (#golang) port of circuits
