### ISSUE TITLE
Worker documentation is outdated

### ISSUE THREAD

**Issue by ke4roh** [circuits/circuits#179]
Llines 4-8 in workers.py (https://github.com/circuits/circuits/blob/master/circuits/core/workers.py) talk of registering workers to pools, not Managers or Components.  They refer to pool code that isn't where it says, and don't seem to align with the factorial example (https://github.com/circuits/circuits/blob/master/examples/factorial.py).  Of course, I could be misreading the whole thing - but I didn't see how to correctly re-word it.

**Comment by prologic** [comment]
Please submit a PR to fix this. I believe the error here is of "legacy" reasons. A `Worker` component these days just wraps around the `multiprocessing` library and provides the same "eventing" interfaces everywhere else you see in circuits. There is no "special" `Pool` components.
