### ISSUE TITLE
Proxy Example

### ISSUE THREAD

**Issue by lachgil** [circuits/circuits#180]
Hey,

I am trying to get the IP address of a connecting client on the proxy example. I am doing so in the connect function by trying to print self.clients[host] but I receive a Keyerror , the key error does give the correct IP.

ERROR <handler[*][connect] (Proxy.connect)> (<connect[server] (<socket._socketobject object at 0x7fb955a589f0>, '192.168.200.100', 56405 )>) (<type 'exceptions.KeyError'>): KeyError('192.168.200.100',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/circuits/core/manager.py", line 661, in _dispatcher
    value = event_handler(*eargs, **ekwargs)
  File "proxy.py", line 49, in connect
    x = self.clients[host]
KeyError: '192.168.200.100'

**Comment by lachgil** [comment]
Connect function ( rest of the code is the same as the proxy example);

    def connect(self, sock, host, port):
        channel = uuid()
        client = Client(
            sock, self.host, self.port, channel=channel
        ).register(self)
	print self.clients[host]

        self.clients[sock] = client

**Comment by spaceone** [comment]
Hi,
you already have the ipaddress in the variable 'host'. You can do whatever you want with it.

**Comment by prologic** [comment]
@spaceone is right. You already have the connected client's host and port as arguments to the event. `host` and `port` respectively.

**Comment by prologic** [comment]
If you adapt your `connect()` event handler to:
```#!python
def connect(self, sock, host, port):
    channel = uuid()
    client = Client(
        sock, self.host, self.port, channel=channel
    ).register(self)
    print("Connected client: {}:{}", host, port)

    self.clients[sock] = client
```

This should solve your problem.
