### ISSUE TITLE
Transmitting large blobs to a Websocket dispatcher causes a disconnect & garbled data

### ISSUE THREAD

**Issue by ri0t** [circuits/circuits#181]
Sending a larger (json-)blob (feels like >10kB is okay for exposing this behaviour) from a Chromium or Firefox Websocket client to a circuits.web.websockets.dispatcher.WebSocketsDispatcher instance breaks the connection and sometimes results in a few garbled read-events being passed on.
### Expected Behaviour

A single read event should be passed on, if the content is not a stream.

I don't exactly know what should happen, if a continuous input stream is sent via websocket, but i plan to use that, soon (for audio transmission).
### Steps to reproduce

Set up a running Server instance with a WebSocketsDispatcher attached.
Using firefox or chromium, open a connection to this dispatcher.
Transmit >10 kb of random data.
-> Socket disconnects
=> Sometimes passes on a garbled read event (not exactly sure how to reproduce this, seems random)

I will try to provide a minimalistic demonstrator by the weekend.
### Environment and Platform
- OS: Linux, Debian Unstable
- Python: 3.5
- circuits: github - master
---

Actually, i sure hope this is just a minor problem in my setup and the problem vanishes when testing with the demonstrator...

**Comment by spaceone** [comment]
Is the problem that the data is splitted into 2 read events due to the size?

**Comment by spaceone** [comment]
Maybe you can also attach the output of the Debugger.

**Comment by ri0t** [comment]
Here's a minimized reproduction app: https://github.com/ri0t/websocketdebugger

**Comment by prologic** [comment]
Any luck debugging what's gong on here?


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by spaceone** [comment]
I fixed this in https://github.com/circuits/circuits/commit/1a7a076223e8846743c3d3666000862cb4c01d5d

**Comment by spaceone** [comment]
Please someone write a test case!

**Comment by prologic** [comment]
You should :)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by spaceone** [comment]
Here is a test case. Did not test if it works because I don't have time. But should work. https://github.com/circuits/circuits/pull/184/commits/1ac3e927bebb7de73fcca508942aaa71ee61e354

**Comment by prologic** [comment]
++


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by spaceone** [comment]
https://github.com/circuits/circuits/pull/184
