### ISSUE TITLE
Encoding errors in POST  requests

### ISSUE THREAD

**Issue by PeteBleackley** [circuits/circuits#186]
### Expected Behaviour

When a POST request with a UTF-8 payload is made, the wrong encoding is used at some point in the processing of the request, leading to the payload being garbled. This is probably something to do with with the storage of `environ['wsgi.input']` in a `BytesIO` object

### Steps to reproduce

Go to https://sahriswiki.org/SandBox and enter text containing non-ascii characters.

### Environment and Platform

Any Sahriswiki instance.

----

**Comment by spaceone** [comment]
Can you copy the exact HTTP request? (e.g. in chromium-developper tools → network → select the request → press "copy as curl" and paste it here).

**Comment by spaceone** [comment]
And what acutally happens? Is there site then just garbage (what does garbage mean)? Is the site not saved at all? Are the characters just stored as latin-1/ISO8859-1 and displayed as two characters?

**Comment by PeteBleackley** [comment]
The utf-8 encoded characters are misinterpreted as latin-1, so for example þ becomes Ã¾.

**Comment by spaceone** [comment]
Okay, reproducible with:
```
curl 'https://sahriswiki.org/+edit/Foo'
   -H 'origin: https://sahriswiki.org'
   -H 'accept-encoding: gzip, deflate, br'
   -H 'accept-language: de,en-US;q=0.8,en;q=0.6'
   -H 'authorization: Basic YWRtaW46YWRtaW4='
   -H 'cookie: circuits.session="a77a2d97db3445ee9fab78766cb54f46/88aa2c97c243562db7939f87f36f54d1d89226d2"; circuits.session="a77a2d97db3445ee9fab78766cb54f46/88aa2c97c243562db7939f87f36f54d1d89226d2"'
   -H 'pragma: no-cache'
   -H 'upgrade-insecure-requests: 1'
   -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36'
   -H 'content-type: application/x-www-form-urlencoded'
   -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
   -H 'cache-control: no-cache'
   -H 'authority: sahriswiki.org'
   -H 'referer: https://sahriswiki.org/+edit/Foo'
   --data 'parent=969d840efcb6&text=Test+%E2%86%92&comment=&action=save'
  --compressed --insecure
```

**Comment by spaceone** [comment]
so after saving u'\xe2\x86\x92' / u'\u2192' (→) the response contains Content-Type: text/html; charset=utf-8 with the data "\xc3\xa2\xc2\x86\xc2\x92".
b'\xc3\xa2\xc2\x86\xc2\x92'.decode('utf-8').encode('latin-1').decode('utf-8')

So it is encoded twice in UTF-8.

**Comment by PeteBleackley** [comment]
I want to bring this issue to the attention of @prologic , the developer of Sahriswiki.

**Comment by prologic** [comment]
Have we tried tofind where this bug is encoding twice? sahriswiki codebase or circuits.web itself?

**Comment by spaceone** [comment]
which python version does sahrisiwki.org use?

**Comment by prologic** [comment]
It was written a long time ago and recently-ish ported to circuits 3.2 -- So it should be running atop Python 2.7 at least. Not sure about @PeteBleackley 's case on Dreamhost servers.

**Comment by spaceone** [comment]
The duplicate encoding is in https://github.com/prologic/sahriswiki/blob/master/sahriswiki/storage.py#L247

**Comment by spaceone** [comment]
A workaround would be, to check for isinstance(text, unicode)

**Comment by prologic** [comment]
Hmm nice find! It's possible that the data is already binary and in the proper encoding at the point it hits `WikiStorage`

**Comment by spaceone** [comment]
Does sahriswiki runs in a daemonized process or is it WSGI? Would you give me access to the system, so I can debug this further?

**Comment by spaceone** [comment]
Here is the circuits.web problem:
https://github.com/circuits/circuits/blob/master/circuits/web/processors.py#L39
```
# python2.7
>>> from circuits.web.processors import QueryStringParser
>>> q = QueryStringParser(b'parent=969d840efcb6&text=Test+%E2%86%92&comment=&action=save'.decode('utf-8'))
>>> q.result
{u'action': u'save', u'comment': u'', u'parent': u'969d840efcb6', u'text': u'Test \xe2\x86\x92'}
>>> q.result['text'].encode('utf-8')
'Test \xc3\xa2\xc2\x86\xc2\x92'
```

**Comment by spaceone** [comment]
i.e. the body is decoded in UTF-8 `before` parsing the content. This removes any possibility to parse the application/x-www-form-ulrencoded syntax correctly as application/x-www-form-urlencode must operate on latin-1 bytes and not on characters. The correct way would be to leave it as bytes and operate on the resulting dictionary by decoding each element in there,

**Comment by spaceone** [comment]
This would be a fix: https://github.com/spaceone/circuits/commit/3527c79b7b8df5e503076b1a8450c74da3e3710b

**Comment by prologic** [comment]
LGTM

**Comment by spaceone** [comment]
Let's see what the tests say.

**Comment by PeteBleackley** [comment]
Thanks @spaceone. Now running the fix on sources.conlang.org
