### ISSUE TITLE
requires.io still links to the bitbucket repository.

### ISSUE THREAD

**Issue by apollo13** [circuits/circuits#190]
Requires.io in README.md:
```
[![Requirements Status](https://requires.io/bitbucket/circuits/circuits/requirements.png?branch=default)](https://requires.io/bitbucket/circuits/circuits/requirements?branch=default)
```
still links to bitbucket. I'd like to update that to github and use versioned requirements, so we have a consistent status of test utils etc when running travis vs locally.

Are you okay with a PR for that or do you want to just remove requires.io (which is kinda useless if requirements do not specify a version ;))

**Comment by prologic** [comment]
Let's remove it :)

**Comment by apollo13** [comment]
PR at #193 -- not sure why github just linked the commit above.
