### ISSUE TITLE
Incorrect use of heapq

### ISSUE THREAD

**Issue by apollo13** [circuits/circuits#198]
PyPy has test failures like this:
```
=================================================================================================================== ERRORS ===================================================================================================================
___________________________________________________________________________________________________ ERROR at setup of test_multiple_values ___________________________________________________________________________________________________

request = <SubRequest 'app' for <Function 'test_multiple_values'>>, manager = <Manager/ 23983:MainThread (queued=0) [R]>, watcher = <Watcher/* 23983:MainThread (queued=0) [S]>

    @pytest.fixture
    def app(request, manager, watcher):
>       app = App().register(manager)

tests/core/test_value.py:69: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
circuits/core/components.py:150: in register
    self.fire(registered(self, self.parent))
circuits/core/manager.py:476: in fireEvent
    self.root._fire(event, channels, **kwargs)
circuits/core/manager.py:453: in _fire
    (priority, next(self._counter), (event, channel)))
/usr/lib/pypy/lib-python/2.7/heapq.py:143: in heappush
    _siftdown(heap, 0, len(heap)-1)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

heap = [], startpos = 0, pos = 1

    def _siftdown(heap, startpos, pos):
>       newitem = heap[pos]
E       IndexError: list index out of range

/usr/lib/pypy/lib-python/2.7/heapq.py:243: IndexError
----------------------------------------------------------------------------------------------------------- Captured stderr setup ------------------------------------------------------------------------------------------------------------
<stopped[*] (<Manager/ 23983:Manager (queued=0) [S]> )>
<registered[*] (<Debugger/* 23983:Manager (queued=0) [S]>, <Manager/ 23983:Manager (queued=1) [R]> )>
<registered[*] (<Watcher/* 23983:Manager (queued=0) [S]>, <Manager/ 23983:Manager (queued=2) [R]> )>
<registered[*] (<App/* 23983:Manager (queued=0) [S]>, <Manager/ 23983:Manager (queued=1) [R]> )>
```

heapq is not threadsafe, so we need to cordinate access with proper locking!

**Comment by apollo13** [comment]
The following seems to fix the current errors (but is probably by no ways complete):
```
diff --git a/circuits/core/manager.py b/circuits/core/manager.py
index 96a63306..9a93140f 100644
--- a/circuits/core/manager.py
+++ b/circuits/core/manager.py
@@ -578,7 +578,8 @@ class Manager(object):
                 self._flush_batch = len(self._queue)
             while self._flush_batch > 0:
                 self._flush_batch -= 1  # Decrement first!
-                priority, count, (event, channels) = heappop(self._queue)
+                with self._lock:
+                    priority, count, (event, channels) = heappop(self._queue)
                 self._dispatcher(event, channels, self._flush_batch)
         finally:
             self._flushing_thread = old_flushing
```

**Comment by apollo13** [comment]
Is there any chance of using https://docs.python.org/2/library/queue.html#Queue.PriorityQueue for the queue as a whole?

**Comment by prologic** [comment]
I believe we found `PriorityQueue` slower than a heapq.

Maybe do some perf benchmarks with `circuits.bench` and compare?

**Comment by apollo13** [comment]
Good point, `PriorityQueue` is most certainly slower than the current usage since it requires a lock all the time. On the other hand, the pypy failures show that the current locking is not enough -- we will at least have to carefully evaluate every access to `_queue` and ensure that they are threadsafe no matter what.

**Comment by prologic** [comment]
Well this is generally only a problem in the test suite which run the
component graph under test in a thread.

Normally in production code you should not be doing this :)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by apollo13** [comment]
> Normally in production code you should not be doing this :)

What exactly? `registerChild` modifies `._queue` and so does `fire`. That means that if a thread executes fire and at the same time you register a new component in the manager's main thread you will have unsynchronized access. That example seems like a valid usecase, ie put some blocking stuff into a thread and fire events from there.

**Comment by prologic** [comment]
circuits was never designed to process events in a multithreaded
environment.
But if you feel we should move towards that we probably can :)

What circuits *does* allow you to do is:

SomeComponentGraph.start()

which runs the component graph in a separate thread
but note that this component graph is distinct from
say your main process/thread's component graph.

The idea is to share events/messages via bridges
or circuits.node


IHMO if we truly support a multi-threaded locking queue of events and
processing we'll significantly impact the performance :/ locks are not
cheap right?



James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

On Wed, Jan 18, 2017 at 2:19 AM, Florian Apolloner <notifications@github.com

**Comment by apollo13** [comment]
On Wed, Jan 18, 2017, at 11:34 AM, James Mills wrote:
> circuits was never designed to process events in a multithreaded
> environment.

Fair enough.

> But if you feel we should move towards that we probably can :)

I do not really have the need or urge to do so.

> which runs the component graph in a separate thread
> but note that this component graph is distinct from
> say your main process/thread's component graph.

Interesting, didn't think about that.

> IHMO if we truly support a multi-threaded locking queue of events and
> processing we'll significantly impact the performance :/ locks are not
> cheap right?

Right, and my comments weren't ment to push you in that direction or
anything. I just got the feeling that this might be something which
should work (tm) given the tests and existing code looks like.

It would be great if you could write a design document for the docs
which explains what works or should work and what is not
supported/untested -- this will prevent confusion of clueless people
like me :D

Nevertheless, the "failures" are real and (even if it is just for the
tests) we should fix them somehow.

**Comment by prologic** [comment]
I agree on all points :)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

On Wed, Jan 18, 2017 at 2:29 PM, Florian Apolloner <notifications@github.com
