### ISSUE TITLE
Useless cache in EventType

### ISSUE THREAD

**Issue by apollo13** [circuits/circuits#202]
Currently EventType looks like this:

```
class EventType(type):

    __cache__ = {}

    def __new__(cls, name, bases, ns):
        key = (cls, name, bases)

        try:
            return cls.__cache__[key]
        except KeyError:
            cls = type.__new__(cls, name, bases, ns)

            setattr(cls, "name", ns.get("name", cls.__name__))

            return cls
```

I couldn't find any code setting something in the `__cache__` -- should we just delete it or actually try using it?

**Comment by prologic** [comment]
Good question. If we don't use this anywhere let's just delete it. I trust
you''ve grokked the codebase and found we don't use this at all :)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by spaceone** [comment]
The whole class is useless in python3 because it is defined via `__metaclass__ = ...`

**Comment by apollo13** [comment]
Guess we should add a test and use `six.with_metaclass` then. I wonder if we even need that metaclass, we can set the `name` by hand in `__new__/__init__` of the class?!

**Comment by spaceone** [comment]
we already do this

**Comment by prologic** [comment]
Probably the meta class might not be required.

**Comment by apollo13** [comment]
seems to be the case according to the tests, I'll remove it for now.
