### ISSUE TITLE
Remove pullaprove and enable branch protection

### ISSUE THREAD

**Issue by apollo13** [circuits/circuits#207]
So given the currently good state of master, I think we could turn on branch protection/status-checks and enforce reviews. (Github docs here: https://help.github.com/articles/about-pull-request-reviews/#required-reviews ) Unless pullaprove does something valuable, I think the Github builtin review features can cover that.

I am assigning to @prologic since it is basically his decision and he has the admin powers :þ

**Comment by prologic** [comment]
Completely agree!

**Comment by prologic** [comment]
Done
