### ISSUE TITLE
test_websockets.py tests fail, waiting to "read"

### ISSUE THREAD

**Issue by Chris-May** [circuits/circuits#236]
### Expected Behaviour

I am experiencing what appears to be a timeout any time a watcher is trying to read a websocket event. 

### Steps to reproduce

I'm using a [slightly modified, standalone version of the framework's test_websockets.py](http://codepad.org/ORjTkx54), where I `from urllib.request import urlopen`, since I'm running under python3.6.

When I run it with py.test, I get a very long running test, and at each `assert watcher.wait("read"...)`, I get an excerpt like this:

```
        client.fire(write(data), "ws")
>       assert watcher.wait("read", channel="ws")
E       AssertionError: assert False
E        +  where False = <bound method Watcher.wait of <Watcher/* 12307:MainThread (queued=0) [S]>>('read', channel='ws')
E        +    where <bound method Watcher.wait of <Watcher/* 12307:MainThread (queued=0) [S]>> = <Watcher/* 12307:MainThread (queued=0) [S]>.wait
```

### Environment and Platform

- OS: OS X
- Python: 3.6.3
- pytest-3.3.1
- circuits: 3.2

----

**Comment by Chris-May** [comment]
Also, when I download the repo and attempt to run tox, I get two failures. The first of which seems related.
```
=========================================== FAILURES ============================================
_____________________________________________ test ______________________________________________

manager = <Manager/ 17686:MainThread (queued=0) [R]>
watcher = <Watcher/* 17686:MainThread (queued=0) [S]>

    def test(manager, watcher):
        app = App()
        process, bridge = app.start(process=True, link=manager)
        assert watcher.wait("ready")

        x = manager.fire(ipc(hello()))

>       assert pytest.wait_for(x, "result")
E       AssertionError: assert None
E        +  where None = <function wait_for at 0x10465e398>(<Value () result=False; errors=False; for <ipc[*] (<hello[*] ( )> channel=None)>>, 'result')
E        +    where <function wait_for at 0x10465e398> = pytest.wait_for

tests/core/test_bridge.py:30: AssertionError
```

**Comment by prologic** [comment]
@Chris-May PR(s) are most welcome! I have no cycles right now to look at this so any help you can invest would be super valuable!

**Comment by spaceone** [comment]
The test works with Python 3.6 now. I am closing this issue.
