### ISSUE TITLE
Adding "auto_add" parameter to circuits.io.notify.add_path()

### ISSUE THREAD

**Issue by kromg** [circuits/circuits#239]
Greetings!
     As mentioned on IRC, I'd like to add a parameter: `auto_add` with default: `True` to `circuits.io.notify.add_path()`. 

The reason is that I noticed that trying to add subpaths manually when they're created can cause event loss. Passing `auto_add=True` to pyintoify seems to solve this problem. 

If you're ok with this, I can submit a PR.

**Comment by spaceone** [comment]
There are syntax errors introduced by this PR for python2. Could you have a look again. E.g:
https://travis-ci.org/circuits/circuits/jobs/427305635
```
E     File "/home/travis/build/circuits/circuits/tests/io/test_notify.py", line 31
E       def create(self, *targets, assert_created=True, dir=False):
E                                               ^
E   SyntaxError: invalid syntax
```

**Comment by spaceone** [comment]
I fixed those syntax errors.
