### ISSUE TITLE
close event argument

### ISSUE THREAD

**Issue by spaceone** [circuits/circuits#24]
why do we fire a close() event without an argument in the net/sockets classes when the global event 'stopped' is executed?

IMHO it would be good to prevent this and close all open sockets by fire close(socket) events if it is required at all.

The io.file component also has a close event which is fired. It would be good to give the fd as argument there. Otherwise each file *must* run in an own channel. There also may be conflicts if there are global event handlers.

**Comment by prologic** [comment]
Hmm I think close() indicates to TCpServer at leatst
to close all client sockets including the server listening socket.


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by spaceone** [comment]
OK
