### ISSUE TITLE
urlparse module can't be found

### ISSUE THREAD

**Issue by Nick-D-H** [circuits/circuits#274]
### Expected Behaviour

When using the multipart.py module, the import of urlparse and the import of parse_qs from cgi both fail resulting in an exception not being caught and termination.

urlparse was replaced by urllib.parse in Python 3, renaming the import to urllib.parse fixes the first part of the issue.

parse_qs is deprecated and no longer a part of cgi as of 19/06/2018 (h[ttps://github.com/python/cpython/commit/698865dcbb302ae742b76be883822f1563764ff9#diff-47cb55e060b6311954134a8a9448613c](https://github.com/python/cpython/commit/698865dcbb302ae742b76be883822f1563764ff9#diff-47cb55e060b6311954134a8a9448613c)).

### Steps to reproduce

Any call to the mutlipart.py module will cause this issue.

### Environment and Platform

- OS: OS X
- Python: 3.8
- circuits: 3.2

**Comment by ri0t** [comment]
I think, i have this suitably fixed in my local copy. At least my python3.8 testsuite runs *that* stuff nice and green.
