### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by spaceone** [circuits/circuits#281]
We should drop Python 2 support in circuits 3.3. (?!)
Python 2.7 is out of maintenance since beginning of 2020:
https://www.python.org/dev/peps/pep-0373/

* This would allow circuits to define coroutines as `async def` functions and change all the `yield` statements to `await`.
* We can drop `circuits.six` the compatibility layer for Python 2.7

**Comment by jhulten** [comment]
Holding to the EOL dates, would you drop for 3.5 and before as well?

https://endoflife.date/python

**Comment by spaceone** [comment]
I am still aware of Python 3.5 systems. Maybe I will wait a litte bit longer, e.g. one year. But it depends on which features we will use in the near future and how active the development is.

**Comment by spaceone** [comment]
@ri0t if you have a starting point i would like to see. Maybe I can invest a weekend to migrate to async/await syntax.

**Comment by spaceone** [comment]
@jhulten the py3.5 system I was aware of is now using py3.7.

**Comment by ri0t** [comment]
> @ri0t if you have a starting point i would like to see. Maybe I can invest a weekend to migrate to async/await syntax.

I will upload something in the next few days.

**Comment by spaceone** [comment]
> > @ri0t if you have a starting point i would like to see. Maybe I can invest a weekend to migrate to async/await syntax.
> 
> I will upload something in the next few days.

I started to work on it in the branch async: https://github.com/circuits/circuits/compare/async?expand=1

**Comment by ri0t** [comment]
That looks quite... interesting! The idea being "just salt everything with `async` and off you go"..? Gotta test that, when i find time.
