### ISSUE TITLE
📣 Migrating off of Github 📣

### ISSUE THREAD

**Issue by prologic** [circuits/circuits#286]
⚠️ Hey all! 👋

As per my [README](https://github.com/prologic/prologic) I will be migrating off of Github this weekend.

If anyone wants to take over this [circuits](https://github.com/circuits) Org, please let me know so I can transfer it to you.

I will not be migrating this org or it's repositories to my own code hosting. I will however take a backup.

Kind regards

James

**Comment by spaceone** [comment]
I want to takeover :-)

**Comment by prologic** [comment]
I guess you are already an owner @spaceone -- Doesn't look like I can _transfer_ the org to you as such. Is there anything bad that will happen if I leave?

**Comment by spaceone** [comment]
![image](https://user-images.githubusercontent.com/1100188/125187343-789fa200-e22f-11eb-83fd-e8aaec620b58.png)
Yes, @Osso and me are owner.
I think you can just leave.

**Comment by spaceone** [comment]
@prologic can you come back into IRC so we can tallk about a few last things. I'm in #circuits on libera.chat or freenode.

**Comment by spaceone** [comment]
I think we can close this issue now. circuits will continue to be hosted on github.
