### ISSUE TITLE
Add Circuits to OpenHatch

### ISSUE THREAD

**Issue by pdurbin** [circuits/circuits#29]
@prologic and I have been talking about adding Circuits to http://openhatch.org

Now that https://github.com/openhatch/oh-mainline/issues/1515 I guess I'll go ahead and try per http://irclogs.shortcircuit.net.au/%23circuits/2015-05-05.log.html#t22:59:06

**Comment by prologic** [comment]
:+1:

**Comment by pdurbin** [comment]
Hmm, I've been logging into OpenHatch with GitHub but now I can't because of https://github.com/openhatch/oh-mainline/issues/1633

I'm going to hold off for now and see if that ticket is resolved soon.

**Comment by prologic** [comment]
Okay :)

**Comment by pdurbin** [comment]
Ok! I'm able to log into OpenHatch now and I just added my first project: http://openhatch.org/projects/dataverse-client-python

@prologic what do you think about that project page? Still want me to go ahead and add one for circuits?

**Comment by prologic** [comment]
Yeah yeah let's do it ;)

**Comment by pdurbin** [comment]
@prologic ok but OpenHatch is oriented around only showing bugs with a "bitesize" or "documentation" label (these are configurable) so it would probably be best to first have at least a few issues labeled like this.

Here's the language they use:

> If you register bug trackers with OpenHatch, we will crawl them for bugs. Those bugs will appear on the volunteer opportunity finder; we'll highlight the ones that are bitesize (meaning, good for newcomers) and those related to non-code tasks (e.g., documentation, graphic design, outreach).

**Comment by prologic** [comment]
Ahh yeah okay no worries. Let's create a few then!? :)

**Comment by prologic** [comment]
Have labeled a few issues:

* https://github.com/circuits/circuits/issues?q=is%3Aopen+is%3Aissue+label%3Abitesize
* https://github.com/circuits/circuits/issues?q=is%3Aopen+is%3Aissue+label%3Adocumentation

**Comment by prologic** [comment]
@pdurbin How are we going with this? I created the labels and labelled a few issues :)

**Comment by pdurbin** [comment]
"Bugtracker successfully edited! New settings should take effect within 24 hours." -- http://openhatch.org/customs/?notification_id=edit-success

http://openhatch.org/projects/circuits

**Comment by prologic** [comment]
Lovely :) Can we close this?

**Comment by prologic** [comment]
Should we be filling in something in the Q&A sections?

**Comment by pdurbin** [comment]
> Should we be filling in something in the Q&A sections?

Not a bad idea.

Let's not close this issue until we've confirmed all is well. I'm having trouble with the first project I added: https://github.com/openhatch/oh-mainline/issues/1435#issuecomment-103437611

**Comment by prologic** [comment]
Good idea; shall you or I fill out some of the Q&A(s)? :)

**Comment by pdurbin** [comment]
@prologic if you would fill out the Q&As that would be great.

**Comment by prologic** [comment]
Sure alright; but I'd appreciate "feedback" when I do in case I don't make it "simple" enough or "easy" enough for newcomers :)

**Comment by prologic** [comment]
I've filled out all the Q&A(s) -- Not sure if the "links" can be improved with titles?

**Comment by prologic** [comment]
@pdurbin Is there still a problem with crawling the issue tracker(s)?

**Comment by prologic** [comment]
> Volunteer opportunities, etc.
> No volunteer opportunities in circuits indexed here yet. Add a bug tracker.

**Comment by pdurbin** [comment]
I'm reaching out at http://irclogs.jackgrigg.com/irc.freenode.net/openhatch/2015-05-31#i_3639877

Please feel free to jump in #openhatch if you'd like to chat with the developers.

**Comment by prologic** [comment]
:+1:

**Comment by pdurbin** [comment]
@willingc when I click http://openhatch.org/+projedit/circuits#edit_bug_trackers this is what I see:

![screenshot from 2015-05-31 18 46 48](https://cloud.githubusercontent.com/assets/21006/7904346/9bacb3d2-07c5-11e5-9252-098d7913c2e3.png)

Which is weird because I know I added the tracker already. How do I know? Well, first I click "GitHub" to see this at http://openhatch.org/customs/add/github?project_id=10671 ...

![screenshot from 2015-05-31 18 47 05](https://cloud.githubusercontent.com/assets/21006/7904361/cfc89668-07c5-11e5-940a-2bdb3ac3a201.png)

... then I click "Back to trackers list" to go to http://openhatch.org/customs/ then change the dropdown to "GitHub" and I see "circuits" already listed:

![screenshot from 2015-05-31 18 47 20](https://cloud.githubusercontent.com/assets/21006/7904384/fd2d3dfc-07c5-11e5-8c2a-c4f33622b0a4.png)

So maybe I did something wrong when first setting this up... maybe somehow I added the circuits project and its bugtracker separately and they aren't associated with each other. Help! :)

**Comment by willingc** [comment]
@pdurbin I'm seeing the same thing on my tests. Bah!

**Comment by prologic** [comment]
So my re-adding a bug tracker isn't going to work right now? :)

**Comment by willingc** [comment]
It seems to me that somewhere along the lines in customs or +projedit that the wrong project id is being passed to a form/function. The circuits project id is 415 but in some places 10761 is appearing. 
![screen shot 2015-05-31 at 5 39 49 pm](https://cloud.githubusercontent.com/assets/2680980/7904717/3186ba42-07bc-11e5-8e80-78fb79396aef.png)
![screen shot 2015-05-31 at 5 40 21 pm](https://cloud.githubusercontent.com/assets/2680980/7904718/363c2e0a-07bc-11e5-84fd-65e08901f8cc.png)
![screen shot 2015-05-31 at 5 50 39 pm](https://cloud.githubusercontent.com/assets/2680980/7904773/5113bc14-07be-11e5-8714-34ecb0a6a4a4.png)
It seems to me that somewhere along the lines in customs or +projedit that the wrong project id is being passed to a form/function. The circuits project id is 415 but in some places 10761 is appearing. 

Here's an example from Open EdX that appear to work correctly/differently though with Jira.
![screen shot 2015-05-31 at 5 52 50 pm](https://cloud.githubusercontent.com/assets/2680980/7904793/ba8ec60c-07be-11e5-9770-2c4e91925133.png)
![screen shot 2015-05-31 at 5 53 24 pm](https://cloud.githubusercontent.com/assets/2680980/7904795/c3cd8190-07be-11e5-84a2-2f3c3b172987.png)

**Comment by prologic** [comment]
Can we do anything to help or can the mis-association be fixed easily?

**Comment by willingc** [comment]
@prologic do you have skills in untangling spaghetti or excellent map reading skills to find buried treasure? :mag: 

Seriously, I'm not sure. Probably need input from Asheesh who has legacy understanding of the code base.

**Comment by prologic** [comment]
What frameworks/libraries does [openhatch](https://github.com/openhatch/oh-mainline) use? I *do* have such "claimed" skills; but it's no trivial matter hunting through large legacy codebase(s) :)

**Comment by willingc** [comment]
Wow! I'm impressed :spaghetti: 

The codebase is essentially Django/Python with CSS/javascript for the front end. The openhatch docs are reasonably well done to get one started and more advanced stuff you can try a search of the docs or ping one of us. There is some legacy oddity between account, profile, project and custom apps. If you look at the models and migrations you will see that stuff has moved around some.

**Comment by prologic** [comment]
This is quite funny barbecue where I currently work we use Django quite heavily and it's a large monolithic codebase (~150k SLOC) and we're still on Django 1.2 :) So I have *some* experience here :) I'll have a poke around when I have some free time :)

**Comment by willingc** [comment]
@prologic Great. Thanks :)

**Comment by prologic** [comment]
bump. What's the latest on this one @pdurbin ?

**Comment by prologic** [comment]
I haven't checked this in a while; how have things panned out?

**Comment by pdurbin** [comment]
> Probably need input from Asheesh who has legacy understanding of the code base.

Hmm, the latest is that we should probably ask @paulproteus for help.

**Comment by prologic** [comment]
What's the latest on this?

**Comment by pdurbin** [comment]
[Maybe](http://irclogs.jackgrigg.com/irc.freenode.net/openhatch/2015-07-31) @paulproteus will have some time this weekend. @prologic he should always be able to find you in #circuits on freenode, I believe.

**Comment by prologic** [comment]
:+1:

**Comment by pdurbin** [comment]
This just in:

> * A new landing page for openhatch.org will be created and simplify access
to useful resources. (It will probably be static HTML.)
> 
> * The existing Django website will be archived as a time capsule of
OpenHatch's past. (The three of us are very grateful to John Morrissey for
the huge task of moving it to Heroku, which makes it sustainable from the
perspective of future time of OpenHatch volunteers.)
> 
> * ...
> 
> * We will try to find another community to house the volunteer opportunity
finder, perhaps the nice people behind http://up-for-grabs.net


[OH-Dev] A new simpler future for openhatch.org web tech - http://lists.openhatch.org/pipermail/devel/2015-December/003872.html

**Comment by prologic** [comment]
Nice :)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by apollo13** [comment]
@prologic Is this still a todo/goal or can we close this?

**Comment by prologic** [comment]
Close it :)
