### ISSUE TITLE
Git Workflow and Merging Pull Requests

### ISSUE THREAD

**Issue by prologic** [circuits/circuits#30]
Now that we're on Github and starting to see more contributors (_thanks everyone!_) -- Let's talk about how we manage Pull Requests and Merging. There's pros/cons to different styles of workflows so let's discuss them here and what we (_the community_) want to see in terms of circuits future development life-cycle(s).

**Comment by spaceone** [comment]
can you add a "Security" label in github?

**Comment by prologic** [comment]
Ahh yes let's do that :)

**Comment by prologic** [comment]
I believe this is done. We pretty much follow Gitflow process.

- 1 branch per feature/fix
- 1 issue per feature/fix
- 1 pull-request per feature/fix
- Squash Mergning
