### ISSUE TITLE
Missing A record for domain circuitsframework.com

### ISSUE THREAD

**Issue by eriol** [circuits/circuits#320]
Hello, I just noticed that the A record for circuitsframework.com is missing, for example using 8.8.8.8 I get:
```
❯ dig @8.8.8.8 circuitsframework.com

; <<>> DiG 9.18.8-1-Debian <<>> @8.8.8.8 circuitsframework.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 60677
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;circuitsframework.com.         IN      A

;; AUTHORITY SECTION:
circuitsframework.com.  1800    IN      SOA     ns1.digitalocean.com. hostmaster.circuitsframework.com. 1644226564 10800 3600 604800 1800

;; Query time: 76 msec
;; SERVER: 8.8.8.8#53(8.8.8.8) (UDP)
;; WHEN: Wed Dec 14 16:43:49 CET 2022
;; MSG SIZE  rcvd: 114
```

**Comment by spaceone** [comment]
Thanks. I don't know about it, @prologic has the ownership of the domains.
I remember darkly that there was also something regarding the domains of the documentation pages: https://docs.readthedocs.io/en/stable/custom-domains.html

**Comment by prologic** [comment]
So yeah I still have the domain. But looks like its pointing nowhere. Where should we point it? 🤔

**Comment by eriol** [comment]
FYI I set the `Homepage` field of circuits' Debian package to this project¹ but I'll be happy to switch it back.

@prologic as proposed by @spaceone I think it's fine to make it point to https://circuits.readthedocs.io

¹ I mean https://github.com/circuits/circuits

**Comment by prologic** [comment]
I used to host it, but that was so long ago I'm not even sure where the source files are, I'll have to have a poke around. In the meantime shall I just point the A record(s) to at least readthedocs.org for the time being? 🤔

**Comment by prologic** [comment]
Great news 🥳 I had forgotten I _actually_ put up the website in [this repo](https://github.com/circuits/circuits.github.io) -- All that's missing is DNS configuration (_don't ask me how this happened!_) -- So I've fixed that now 👌 Assuming i did everything right, this should start working again 🤞

**Comment by eriol** [comment]
@spaceone oh yes, I adopted the package in 2016, it was already packaged: https://tracker.debian.org/pkg/circuits

@prologic I can confirm it's working now¹, many thanks! With the next upload I will switch back the Homepage field to https://circuitsframework.com

I'm closing this since it's fixed, many thanks!

¹ It needed a bit to load, but I will open a ticket on the website repository! :smile:

**Comment by eriol** [comment]
FYI https://github.com/circuits/circuits.github.io/issues/3
