### ISSUE TITLE
Couple of questions the documentation seems to be lacking

### ISSUE THREAD

**Issue by KIC** [circuits/circuits#323]
First of all, I really like this framework!

Now, after some "hello world" and before my use case, I have a couple of questions the documentation can't answer for me.
I was wondering if I should use the mailing list or SO, but then I decided to file an issue because this is really something that I think should be documented and not just answered on the spot. 

1. if more than one bound function (aka event handlers) accesses an object variable, do I have to use a thread lock? Like is the access to `self.some_state` safe in the following example:

```pyhton

class Foo(Component):

    def __init__(self,):
        super().__init__()
        self.some_state = []
        
    def handler_1(self, event):
        self.some_state.append(event)
    
    def handler_2(self, event):
        self.some_state.remove(event)

```

2. if I need to process time-generated events is the ordering of the events guaranteed or can a recent event be faster than a previous event?  like is it guaranteed that `fire(Event(1)); fire(Event(2))` Event 1 is always processed before Event 2?

3. sometimes I need to emit events inside another event handler and be sure that all these events are processed fully (by all handlers) before I can continue. Do you think this is the preferred solution?

```python
        for asset in asset_weights.keys():
            _ = yield self.fire(TickDataClock(asset))

        # we are sure that all clocks have ticked
        process(origin_event)
```

or is there any kind of `await(all_fired_events)`? Because I think the yield assignment approach is rather confusing. That is because now the original event handler yields several `None`'s just because it wants to wait for some sub-events. Now, how can an event handler know how many None yields it has to wait for? This is really confusing to me. I think it would actually be nice if an Event sub-class itself could be flaged as synchronous (or blocking).

**Comment by spaceone** [comment]
Hi KIC,

1. threads aren't involved in that code. if you use threading you have to lock it yourself.
2. the events are processed in the incoming order, yes. but it also depends on other factors like how many handlers does the event have and are these handlers yielding coroutines or not? so event2 could be finished before event1.
3. do you already know `self.call()` ? and `self.wait()`? in your current code `process` would be called without the `TickDataClock`  events being processed completely.

we have to do https://github.com/circuits/circuits/issues/306 so that the framework can be used in a modern fashion.

**Comment by KIC** [comment]
clear on 1 and 2, thanks. 

ad 3) well this indeed works as expected:
```python
from time import sleep

from circuits import Component, Event, handler, Debugger, Worker


class TestEvent(Event):

    def __init__(self, *args, **kwargs):
        super().__init__("foo", *args, **kwargs)

class SynchronTestEvent(Event):

    def __init__(self, version, *args, **kwargs):
        super().__init__(version, *args, **kwargs)


class App(Component):

    def __init__(self):
        super().__init__()

    @handler(TestEvent.__name__)
    def on_test(self, x):

        for v in range(3):
            _ = yield self.fire(SynchronTestEvent(v))

        print("now process x", x)

    @handler(SynchronTestEvent.__name__)
    def on_snyc_test(self, x):
        sleep(0.5)
        print("wait for me", x)

if __name__ == '__main__':
    app = App() + Debugger()
    app.start()
    app.fire(TestEvent())
    app.join()
```

prints:
```
<registered[*] (<Debugger/* 2415298:App (queued=0) [S]>, <App/* 2415298:App (queued=2) [R]> )>
<started[*] (<App/* 2415298:App (queued=1) [R]> )>
<TestEvent[*] ('foo' )>
<SynchronTestEvent[*] (0 )>
wait for me 0
<SynchronTestEvent[*] (1 )>
wait for me 1
<SynchronTestEvent[*] (2 )>
wait for me 2
now process x foo
```

While this doesn't:
```python

from time import sleep

from circuits import Component, Event, handler, Debugger, Worker


class MasterEvent(Event):
    pass


class TestEvent(Event):

    def __init__(self, *args, **kwargs):
        super().__init__("foo", *args, **kwargs)

class SynchronTestEvent(Event):

    def __init__(self, version, *args, **kwargs):
        super().__init__(version, *args, **kwargs)


class App(Component):

    def __init__(self):
        super().__init__()

    @handler(MasterEvent.__name__)
    def on_master(self):
        _ = yield self.fire(TestEvent())
        print("this should be last")

    @handler(TestEvent.__name__)
    def on_test(self, x):

        for v in range(3):
            _ = yield self.fire(SynchronTestEvent(v))

        print("now process x", x)

    @handler(SynchronTestEvent.__name__)
    def on_snyc_test(self, x):
        sleep(0.5)
        print("wait for me", x)



if __name__ == '__main__':
    app = App() + Debugger()
    app.start()
    #app.fire(TestEvent())
    app.fire(MasterEvent())
    app.join()
```
```
<registered[*] (<Debugger/* 2415480:App (queued=0) [S]>, <App/* 2415480:App (queued=2) [R]> )>
<started[*] (<App/* 2415480:App (queued=1) [R]> )>
<MasterEvent[*] ( )>
<TestEvent[*] ('foo' )>
this should be last
<SynchronTestEvent[*] (0 )>
wait for me 0
<SynchronTestEvent[*] (1 )>
wait for me 1
<SynchronTestEvent[*] (2 )>
wait for me 2
now process x foo
```

Of course, you cant iterate over None:
```
    def on_master(self):
        for x in self.fire(TestEvent()):
            pass

        print("this should be last")
```

is not working.

Sorry I am just not able to get anything working with `call()` and `wait()`, could you provide an example that is working across multiple levels.

**Comment by spaceone** [comment]
you can do `yield self.call(…)` instead of `self.fire(…)` which will guarantee, that the even `…` is finished when the code steps back into that coroutine.
`call()` is just an equivalent for:
```
self.fire(foo())
yield self.wait("foo")
```

**Comment by KIC** [comment]
Nice, thx works as expected.
