### ISSUE TITLE
TravisCI blocks Pull Requests

### ISSUE THREAD

**Issue by spaceone** [circuits/circuits#324]
TravisCI blocks Pull Requests.
Every PR shows this message which prevents merging (can be skipped by an Admin):
![image](https://user-images.githubusercontent.com/1100188/210535192-22fe1305-b75c-4dd7-98c9-f873de3a76e6.png)

We removed all TravisCI config from the repository when we went to GitHub Actions.
I also cannot see any settings regarding TravisCI.

**Comment by spaceone** [comment]
@prologic do you have an idea?

**Comment by spaceone** [comment]
ah fixed via https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154

**Comment by prologic** [comment]
I think you should switch to GitHub actions 👌

**Comment by spaceone** [comment]
> I think you should switch to GitHub actions ok_hand

yes, that's already done. Sorry for the noise.
