### ISSUE TITLE
Recent changes but no PyPi release

### ISSUE THREAD

**Issue by bobleckelibm** [circuits/circuits#326]
@spaceone hello! Nice to see that someone is still working at least somewhat in this repo... I notice that you've been working on things here over the last few years. But the PyPi version of this package hasn't been updated since Oct 2021. I'm wondering if there is a plan to ever release any of the modifications that you've made? I'm sure plenty of them are useful, most useful to me right now is that you fixed the `from imp import reload` in utils.py. Right now, without that, I cannot use circuits on Python 3.12.

**Comment by spaceone** [comment]
I will see that I do a minor release in the next time.

**Comment by bobleckelibm** [comment]
thanks @spaceone I appreciate the quick response.

**Comment by spaceone** [comment]
I just released circuits 3.2.3: https://pypi.org/project/circuits/3.2.3/

Changelog: https://github.com/circuits/circuits/blob/master/CHANGES.rst
