### ISSUE TITLE
Commit f22e626 broke test

### ISSUE THREAD

**Issue by y0no** [circuits/circuits#35]
As I say on IRC to @prologic, the last circuit commit (https://github.com/circuits/circuits/commit/f22e62674bae57c1948c14651c32065e9916f9f7) seems to broke some tests after being merged with master branch.

@treemo are you on it ?

**Comment by prologic** [comment]
If one of you could look into this and submit a PR that fixes this that would be great :) I'm at work atm so won't be able to look at it till tonight AEST :)

**Comment by prologic** [comment]
See: #34

**Comment by treemo** [comment]
See: https://github.com/circuits/circuits/pull/38

**Comment by prologic** [comment]
Is this closed by #38?

**Comment by y0no** [comment]
Tests seems to pass with python 3.4.3 and python 2.7.9. It's good for me.

**Comment by prologic** [comment]
Awesome :) We have [Travis CI](https://github.com/circuits/circuits/issues/33) setup now too so hopefully we'll get all tests passing across all supported versions :)

**Comment by y0no** [comment]
Currently some tests fail under python 2.7 and 3.4 because of SSL library changes.

**Comment by prologic** [comment]
kk can we open a new issue regarding that?
