### ISSUE TITLE
Document Devleopment Environment

### ISSUE THREAD

**Issue by prologic** [circuits/circuits#41]
See: http://circuits.readthedocs.org/en/latest/dev/index.html

What's missing is a step-by-step guide to setting up a reliable/repeatable development environment with:

* virtualenv
* pip
* installing dev requirements
* running unit tests

**Comment by prologic** [comment]
A ``CONTRIBUTING.md`` int he top-level repo should be fine right?

**Comment by spaceone** [comment]
yes

**Comment by prologic** [comment]
Great :) I'll try writing one up tonight :)

@pdurbin will be pleased as I think he's mentioned we should have such a document in the repo too :)

@pdurbin any ideas on style/template/example?

**Comment by pdurbin** [comment]
Don't look at http://guides.dataverse.org/en/latest/developers until I've had a chance to work on https://github.com/IQSS/dataverse/issues/912 which should be soon! :)

**Comment by prologic** [comment]
Haha why? WHat's wrong with it :)
