### ISSUE TITLE
event.stop() prevents return into coroutine

### ISSUE THREAD

**Issue by spaceone** [circuits/circuits#45]
See failing test case: https://github.com/circuits/circuits/commit/75ff37beac4555fcfe97a68fc364bb0824aac018

**Comment by spaceone** [comment]
Well, there are of course also use cases where this is the wanted behavior.
I would say we leave it as is but add some extra functionality to an event which can stop that further handlers for that event are processed.

**Comment by prologic** [comment]
For example? I've used a few JS Event API(s) we could do something similar?

**Comment by spaceone** [comment]
test case was broken...
