### ISSUE TITLE
Improve control of displaying teh circuits.web banner (expose_circuits)

### ISSUE THREAD

**Issue by prologic** [circuits/circuits#49]
Many of the tests are failing with:

```#!python
    @property
    def expose_circuits(self):
>       return self.__expose_circuits
E       AttributeError: 'Server' object has no attribute '_BaseServer__expose_circuits'
```

I have a proposed fix coming shortly but which also changes the attribute name and keyword argument to ``display_banner``. Is that okay @treemo ? (*I think it's a bit more clear this way and more in-line with other things like SMTP Banner, etc*)

See also: #39

**Comment by treemo** [comment]
i'm ok, this name is better :)
