### ISSUE TITLE
Implement Component.__nonzero__ proper

### ISSUE THREAD

**Issue by spaceone** [circuits/circuits#51]
BaseComponent/Manager implements __bool__/__nonzero__ which returns True if there are pending events.
As it is a API to inherit from BaseComponent this is error prone.
I needed a lot time to debug the lines:
```
if arg:
    foo()
```
which failed but worked finally with ```if arg is not None:``` (where arg is a component, e.g. event.value.manager).

We should not overwrite pythons expected default behavior in the API and instead hide internals like those.

**Comment by prologic** [comment]
Where if any of is this used and relied upon internally?

**Comment by spaceone** [comment]
At least in circuits/tests/core/test_core.py

**Comment by prologic** [comment]
Seems we removed this already

**Comment by spaceone** [comment]
hmm? Nothing is done here, yet.
__bool__/__nonzero__ is still implemented

And the mentioned test case also still contains:
 27 while app:
 28     app.flush()

**Comment by prologic** [comment]
Show me? I grepped the codebase and could not find anything that implements this!

**Comment by spaceone** [comment]
circuits/circuits/core/manager.py
```
 230     def __len__(self):
 231         """x.__len__() <==> len(x)
 232 
 233         Returns the number of events in the Event Queue.
 234         """
 235 
 236         return len(self._queue)
```

**Comment by prologic** [comment]
Ahh yes but this doesn't implement ``__nonzero__``. This gives you the queue length (*no. of events in the queue*) of a component (*usually you want ``len(self.root)``*)

**Comment by prologic** [comment]
You *should* still be able to implement your own ``__nonzero__`` however in a component subclass.

**Comment by spaceone** [comment]
```
>>> class Foo(object):                                                                                                                                                                                                                                                           
...     def __len__(self):                                                                                                                                                                                                                                                       
...         return 0                                                                                                                                                                                                                                                             
... 
>>> 
>>> 
>>> f = Foo()
>>> bool(f)
False
```

**Comment by prologic** [comment]
So I'm proposing the following new public API(s):

* ``.empty``
* ``.qsize``

both properties.

Okay with this?

**Comment by spaceone** [comment]
uhm, no? I would leave `__len__` as it is. But i would implement `__bool__` and `__nonzero__` to return True.

**Comment by prologic** [comment]
Oh man! Is that what you meant all along? *sigh* We need to *improve* are communications! I was totally lost as to what you were proposing :)

Let's try this again!

```#!bash
git checkout -- .
``

LOL

**Comment by prologic** [comment]
All [this work](https://gist.github.com/304c2a364c467994bb9c) I did for nothing and all the tests passing too :) Haha :)

**Comment by spaceone** [comment]
I'm really sorry :D You can use sed now to replace it: s/app.empty/len(app)/g. 
Using properties here would be a disadvantage as they slow down the whole thing.
