### ISSUE TITLE
not possible to hook before socket closing on SSL error

### ISSUE THREAD

**Issue by spaceone** [circuits/circuits#53]
It is currently not possible to react on SSL socket errors (which are happening during handshake). The client socket is immediately closed.

I would like to write response data into that socket if the handshake fails. Also I would like to get the broken bytes send as SSL handshake from the client.

See https://github.com/spaceone/circuits.http/commit/6ee348690a4a4e7ae28ff6b0eb4d44cf163e1551 for an example on the use case.
Apache HTTPd is capable of this functionality.

**Comment by prologic** [comment]
Yeah I agree; the handshake should happen in an event handler IHMO. We should refactor this

**Comment by prologic** [comment]
Closing in favour of #114
