### ISSUE TITLE
Memory leak inside circuits manager ?>

### ISSUE THREAD

**Issue by y0no** [circuits/circuits#54]
Hi,
after few tests,  it seems that circuits consume much more memory when using callEvent, than when using FireEvent with a waiting loop. To be more clear, I have written two script that process the same tasks, and theses scripts measure there memory consumption over iteration.

The two scripts can be found here: https://gist.github.com/y0no/09826e83e643bc0f98c2

One is using "call" and the other "fire". After execution here is the memory consumption for fire:
![Memory consumption on fire](http://i.imgur.com/UsBQm1H.png)

And this one for call:
![Memory consumption on call](http://i.imgur.com/5umc5nG.png)

As you can see call function use a lot more memory than fire.

In a perfect world, the memory consumption shoulld be the same in each case. And in a really perfect world the memory should not grow over time, because after each task the memory should be released.

After a few investigation, it seems that the issue come from manager who don't correctly stop iterator. It could be great to really stop iterator with a "StopIteration" exception that allow garbage collector to do its job.

**Comment by prologic** [comment]
This is great; Just to be clear however your test case does take into account it's own objects? e.g: appending to a list will increase memory usage over time :)

**Comment by y0no** [comment]
Update: A first attempt to improve memory consumption can be found [here](https://github.com/circuits/circuits/blame/master/circuits/core/manager.py#L775)

If we add a ``next(task)`` at the line 775), we allow garbage collector to do its job after CallValue has been return by our task, because a CallValue object is the last thing that a task will return before finish as can see [here](https://github.com/circuits/circuits/blob/master/circuits/core/manager.py#L510)

Of course, it is not the solution, but it prove that the issue seemss to come from iterator usage.

**Comment by y0no** [comment]
The test case doesn't take into account it's own object. Even if we don't use list to store memory measure, we have seen in production issues related to memory. 

The test case is currently here to show the difference between call and fire event when they are used in the same usage. Indeed, it will be great to write a real test case to get more precise measure.

**Comment by prologic** [comment]
I'm going to have a bit of a play with your test scripts here and see what we can do :)

I do want this fixed ASAP as a matter of **importance** :)

**Comment by spaceone** [comment]
cc

**Comment by prologic** [comment]
Is this test valid?

``test_memory_usage.py``:
```#!python
import pytest


from operator import attrgetter


import resource


from circuits import Event, Component


class test(Event):
    """test Event"""


class App(Component):

    def test(self):
        return "Hello World!"

    @property
    def memory(self):
        return resource.getrusage(resource.RUSAGE_SELF).ru_maxrss


@pytest.fixture
def app(request):
    app = App()

    def finalizer():
        app.stop()

    request.addfinalizer(finalizer)

    app.start()

    return app


def test_fire(app):
    xmem = app.memory
    xs = []
    for _ in range(10):
        xs.append(app.fire(test()))
    ymem = app.memory
    assert ymem == xmem

    while app:
        app.flush()

    zmem = app.memory
    assert zmem == xmem

    assert all(x == "Hello World!" for x in map(attrgetter("value"), xs))
```

*Test run:*
```#!bash
$ py.test -x -s -v tests/core/test_memory_usage.py
======================================= test session starts ========================================
platform linux2 -- Python 2.7.9 -- py-1.4.28 -- pytest-2.7.1 -- /home/prologic/.virtualenvs/circuits/bin/python
rootdir: /home/prologic/work/circuits, inifile: 
plugins: cov
collected 1 items 

tests/core/test_memory_usage.py::test_fire PASSED

===================================== 1 passed in 0.01 seconds =====================================
```

**Comment by treemo** [comment]
launch 10 event is to small for measure the memory leak

test_memory_leak.py:

```Python
from circuits import Event, Component
import pytest
import resource


class test(Event):
    """test Event"""


class test_call(Event):
    """test Event"""


class App(Component):
    def test(self):
        return 'Hello World!'

    def test_call(self):
        for _ in range(10000):
            yield self.call(test())

    @property
    def memory(self):
        return resource.getrusage(resource.RUSAGE_SELF).ru_maxrss


@pytest.fixture
def app(request):
    app = App()

    def finalizer():
        app.stop()

    request.addfinalizer(finalizer)
    app.start()
    return app


def test_memory_call(app):
    start_memory = app.memory
    event = test_call()

    for _ in range(10000):
        for _ in app.call(event):
            pass

    assert app.memory == start_memory


def test_memory_fire(app):
    start_memory = app.memory

    for _ in range(10000):
        app.fire(test())

    while len(app):
        pass

    assert app.memory == start_memory


def test_memory_wait(app):
    start_memory = app.memory
    event = test()

    for _ in range(10000):
        for _ in app.waitEvent(event):
            pass

    assert app.memory == start_memory```

Test run:
```Shell
py.test tests/core/test_memory_leak.py -v
================================================================= test session starts =================================================================
platform linux -- Python 3.4.3 -- py-1.4.26 -- pytest-2.6.4 -- /usr/bin/python3
collected 3 items 

tests/core/test_memory_leak.py::test_memory_fire FAILED
tests/core/test_memory_leak.py::test_memory_wait FAILED
tests/core/test_memory_leak.py::test_memory_call FAILED

====================================================================== FAILURES =======================================================================
__________________________________________________________________ test_memory_fire ___________________________________________________________________

app = <App/* 10343:MainThread (queued=0) [R]>

    def test_memory_fire(app):
        start_memory = app.memory
    
        for _ in range(10000):
            app.fire(test())
    
        while len(app):
            pass
    
>       assert app.memory == start_memory
E       assert 31924 == 21832
E        +  where 31924 = <App/* 10343:MainThread (queued=0) [R]>.memory

tests/core/test_memory_leak.py:47: AssertionError
__________________________________________________________________ test_memory_wait ___________________________________________________________________

app = <App/* 10343:MainThread (queued=0) [R]>

    def test_memory_wait(app):
        start_memory = app.memory
        event = test()
    
        for _ in range(10000):
            for _ in app.waitEvent(event):
                pass
    
>       assert app.memory == start_memory
E       assert 50724 == 32148
E        +  where 50724 = <App/* 10343:MainThread (queued=0) [R]>.memory

tests/core/test_memory_leak.py:58: AssertionError
__________________________________________________________________ test_memory_call ___________________________________________________________________

app = <App/* 10343:MainThread (queued=7830) [R]>

    def test_memory_call(app):
        start_memory = app.memory
        event = test_call()
    
        for _ in range(10000):
            for _ in app.call(event):
                pass
    
>       assert app.memory == start_memory
E       assert 83608 == 50732
E        +  where 83608 = <App/* 10343:MainThread (queued=7831) [R]>.memory

tests/core/test_memory_leak.py:69: AssertionError
============================================================== 3 failed in 4.77 seconds ===============================================================
```

**Comment by prologic** [comment]
Ahh Thank you :) This is a really nice test! I'll get on this :+1:

**Comment by spaceone** [comment]
I also observed that using "yield self.call()" is about 2 times slower(!) than using self.fire()

**Comment by prologic** [comment]
@spacone What does that have to do with "memory leaks"? :) If that's the case and it can be demonstrated with a test case we should raise *that* as a separate issue :)

**Comment by prologic** [comment]
i'm still working on this in [circuits/circuits#bug-fix#54](https://github.com/circuits/circuits/tree/bug-fix%23%2354)

**Comment by y0no** [comment]
thanks to working on it, I hope this issue can be fixed quickly :+1:

**Comment by prologic** [comment]
Yeah I'll try and dedicate the next few nights to this :) :+1:

**Comment by prologic** [comment]
I'm still working on thie (*sorry little slow!*); I'll try to get this done soon!

**Comment by prologic** [comment]
@Osso: You said you'd have a crack at this one? :)

**Comment by myaut** [comment]
I'm not sure if this related to this bug, but I'm also facing memory leakage. I have setup a thread that periodically dumps `root.__dict__` and noticed that `ClassName._on_done` are accumulated in _cache.

It seems that problem is due to `_on_done` not being cleaned up from handlers if timeout is not set. I made following change in waitEvent:

        # if not state['timeout']:
        # self.removeHandler(_on_done_handler, "%s_done" % event_name)
        self.removeHandler(_on_done_handler, "%s_done" % event_name)

and it does seem to stop a leakage.

Note that default value of timeout is `-1` and `(not -1) is False`

**Comment by prologic** [comment]
Could you provide a PR to this effect? That would be wonderful! Also I think you are right IIRC (*last time I was digging in to this*). What I couldn't do was write a unit test that a) demonstrated the leakage consistently and b) Fix that unit test to show the leakage fixed. -- Maybe you might have better luck :)
