### ISSUE TITLE
system exit code

### ISSUE THREAD

**Issue by spaceone** [circuits/circuits#55]
one can raise SystemExit in a handler. The code then calls self.stop().
but the argument of SystemExit (which may be a int) is not evaluated.

$ python
>>> raise SystemExit(3)
$ echo $?
3

**Comment by spaceone** [comment]
circuits.app.daemonize exit code for example is wrong when errors during fork() happens

**Comment by prologic** [comment]
Cool let's fix this :-1:

**Comment by prologic** [comment]
I have a patch for this but I'm too lazy right now to write a test for this :)
Do we need one? :) (*it was more a lacking feature*)

```#!diff
diff --git a/circuits/core/manager.py b/circuits/core/manager.py
index 57595f4..e5f0c66 100644
--- a/circuits/core/manager.py
+++ b/circuits/core/manager.py
@@ -627,8 +627,10 @@ class Manager(object):
                     value = event_handler(event, *eargs, **ekwargs)
                 else:
                     value = event_handler(*eargs, **ekwargs)
-            except (KeyboardInterrupt, SystemExit):
+            except KeyboardInterrupt:
                 self.stop()
+            except SystemExit as e:
+                self.stop(e.code)
             except:
                 etype, evalue, etraceback = _exc_info()
                 traceback = format_tb(etraceback)
@@ -754,7 +756,7 @@ class Manager(object):
         if getattr(self, "_process", None) is not None:
             return self.__process.join()
 
-    def stop(self):
+    def stop(self, code=0):
         """
         Stop this manager. Invoking this method causes
         an invocation of ``run()`` to return.
@@ -778,6 +780,8 @@ class Manager(object):
             for _ in range(3):
                 self.tick()
 
+        raise SystemExit(code)
+
     def processTask(self, event, task, parent=None):  # noqa
         # XXX: C901: This has a high McCabe complexity score of 16.
         # TODO: Refactor this method.
@@ -837,8 +841,10 @@ class Manager(object):
             elif event.waitingHandlers == 0:
                 event.value.inform(True)
                 self._eventDone(event)
-        except (KeyboardInterrupt, SystemExit):
+        except KeyboardInterrupt:
             self.stop()
+        except SystemExit as e:
+            self.stop(e.code)
         except:
             self.unregisterTask((event, task, parent))
 
```

**Comment by spaceone** [comment]
KeyboardInterrupt should be 1.

**Comment by prologic** [comment]
Really? Why?

**Comment by spaceone** [comment]
hmm, it is regular behavior:

# python -c 'while True: pass'
^CTraceback (most recent call last):
  File "<string>", line 1, in <module>
KeyboardInterrupt
# echo $?
1

Well, I am now unsure about it :D

**Comment by spaceone** [comment]
It depends a little bit on the application.

**Comment by prologic** [comment]
See the thing is an application can catch the ``signal()`` event and prevent a ``^C`` anyway or do something else with it.

So we should not call ``self.stop(1)`` here in this case; only for caught ``SystemExit(0)`` that got bubbled up to the dispatcher and the system/app is *going down*.

**Comment by spaceone** [comment]
yes, you are right

**Comment by prologic** [comment]
So all we need now is a unit test for this and we're golden :) I'll commit it to a branch and push it up as-is now anyway...

**Comment by spaceone** [comment]
ok, i'll write one

**Comment by prologic** [comment]
Sweet :) commit it to the ``system_exit`` branch? :)

**Comment by prologic** [comment]
I think it could be a similar test to [``test_app.py``](https://github.com/circuits/circuits/blob/master/tests/app/test_daemon.py)

**Comment by spaceone** [comment]
https://github.com/spaceone/circuits/commit/2529555d8cdde86180fa22c6d1fc41ea2b81117f

**Comment by prologic** [comment]
Damnit I can't work out how to merge your commit into system_exit. Any ideas?
