### ISSUE TITLE
Redesigning circuits.web

### ISSUE THREAD

**Issue by prologic** [circuits/circuits#56]
We should discuss how we can redesign circuits.web and improve it's internals and higher level API(s).

We could integrate with [HTTOOP](https://github.com/spaceone/httoop)
but my only concern with this is feature parity and API compatibility.

See: #48

**Comment by spaceone** [comment]
I find this still relevant. I recently started to port httoop to python3 compatibility.
If you care about feature parity: httoop includes way more features than this current implementation.
About API compatibility: The HTTP objects are very similar except for some details and unecessary things.

**Comment by prologic** [comment]
I'm jus tcleaing old issues up. IF this is still important to you; put up a
PR :) I don't have any attachment to circuits.web (haven't for some time
now) Thanks!

James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au
