### ISSUE TITLE
wait() should work with event instance

### ISSUE THREAD

**Issue by spaceone** [circuits/circuits#60]
It would be nice to wait for the completition of a very specific event instead of just a named event as this name may exists multiple times concurrent.

**Comment by prologic** [comment]
There are two ways we *can* make this happen IHMO.

**Case #1:** *Waiting on the event's value*
```
#!python
def test(self, *args):
    v = self.fire(foo())
    yield self.wait(v)
```

**Case #2:** *Waiting on an event instance*
```
#!python
def test(self, *args):
    e = foo()
    v = self.fire(foo())
    yield.wait(e)
```

I believe both *could* be valid use-cases; but they both have very different semantics.

**Comment by spaceone** [comment]
can you please explain the differing semantic?
Case 2 would allow to wait until the event is completely processed
I can't image what Case 1 could be.

**Comment by prologic** [comment]
Well I guess they *could* possibly mean the same thing; but teh first waits for the event's value (*which is also unique to that event*).

**Comment by prologic** [comment]
I'm attempting to write a patch to support this :)

**Comment by prologic** [comment]
Turns out we've always had support for this; but there seems to be a bug.

**Comment by prologic** [comment]
Hmm @spaceone There is no bug?

``test_call_wait_instance.py``:
```#!python
#!/usr/bin/env python

import pytest

from circuits import handler, Component, Event


class wait(Event):
    """wait Event"""

    success = True


class hello(Event):
    """hello Event"""

    success = True


class App(Component):

    @handler("wait")
    def _on_wait(self):
        e = hello()
        x = self.fire(e)
        yield self.wait(e)
        yield x.value

    def hello(self):
        return "Hello World!"


@pytest.fixture
def app(request, manager, watcher):
    app = App().register(manager)
    assert watcher.wait("registered")

    def finalizer():
        app.unregister()

    request.addfinalizer(finalizer)

    return app


def test_wait_instance(manager, watcher, app):
    x = manager.fire(wait())
    assert watcher.wait("wait_success")

    value = x.value
    assert value == "Hello World!"
```

*Test run:*
```#!bash
$ py.test -x -s -v tests/core/test_call_wait_instance.py 
======================================= test session starts ========================================
platform linux2 -- Python 2.7.9 -- py-1.4.28 -- pytest-2.7.1 -- /home/prologic/.virtualenvs/circuits/bin/python
rootdir: /home/prologic/work/circuits, inifile: 
plugins: cov
collected 1 items 

tests/core/test_call_wait_instance.py::test_wait_instance <registered[*] (<Debugger/* 14285:Manager (queued=0) [S]>, <Manager/ 14285:Manager (queued=3) [R]> )>
<registered[*] (<Watcher/* 14285:Manager (queued=0) [S]>, <Manager/ 14285:Manager (queued=2) [R]> )>
<registered[*] (<App/* 14285:Manager (queued=0) [S]>, <Manager/ 14285:Manager (queued=1) [R]> )>
<wait[*] ( )>
<hello[*] ( )>
<hello_done[*] ('Hello World!' )>
<hello_success[*] (<hello[*] ( )>, 'Hello World!' )>
<wait_success[*] (<wait[*] ( )>, 'Hello World!' )>
PASSED<prepare_unregister[*] (<App/* 14285:Manager (queued=0) [S]> )>
<prepare_unregister[*] (<Watcher/* 14285:Manager (queued=0) [S]> )>
<prepare_unregister_complete[<App/* 14285:Manager (queued=0) [S]>] (<prepare_unregister[*] (<App/* 14285:Manager (queued=0) [S]> )>, None )>
<prepare_unregister_complete[<Watcher/* 14285:Manager (queued=0) [S]>] (<prepare_unregister[*] (<Watcher/* 14285:Manager (queued=0) [S]> )>, None )>
<unregistered[*] (<App/* 14285:Manager (queued=0) [S]>, <Manager/ 14285:Manager (queued=2) [R]> )>
<unregistered[*] (<Watcher/* 14285:Manager (queued=0) [S]>, <Manager/ 14285:Manager (queued=1) [R]> )>


===================================== 1 passed in 0.62 seconds =====================================
```

**Comment by prologic** [comment]
I'm confused :) What about this *doesn't* work?

**Comment by spaceone** [comment]
Try this way:
 ```
      for i in range(10):
          self.fire(hello(i))
       e = hello(False)
        x = self.fire(e)
        yield self.wait(e)
      for i in range(10):
          self.fire(hello(i))
```
plus:
```
@handler('hello')
def _on_hello(self, sleep):
   if sleep:
      import time
      time.sleep(sleep)
```

**Comment by spaceone** [comment]
https://github.com/spaceone/circuits.http/blob/master/circuits/http/server/routing/router.py#L19

**Comment by prologic** [comment]
Both pass :)

**Comment by prologic** [comment]
Hmm I don't quite fully understand your code/use-case per se.

It's getting late; I'll look into this more later...

But if you could play around with this unit test and demonstrate a particular failure in some use-case?

**Comment by spaceone** [comment]
hmm. I tracked down one of my problem:
if you fire an event into another channel and wait for it it never returns into the coroutine. I fixed this by adding the channels to the wait call. But IHMO this is bad design by circuits.
I would at least suggest the following patch:
```
diff --git a/circuits/core/manager.py b/circuits/core/manager.py
index dda92e3..c263252 100644
--- a/circuits/core/manager.py
+++ b/circuits/core/manager.py
@@ -495,6 +495,7 @@ class Manager(object):
         if isinstance(event, Event):
             event_object = event
             event_name = event.name
+            channels = event.channels or channels
         else:
             event_object = None
             event_name = event
```

But circuits should also detect such wrong usage (if there was something yield which will cause a coroutine to never return).

**Comment by spaceone** [comment]
OK, it seems that the origin of this issue works with circuits. Waiting for a event instance is possible → INVALID.
But other coroutines have a higher(random) priority, so if a event is finished other coroutines which doesn't wait for an event might have a higher priority than jumping back into the coroutine. This could be improoved to speed up applications.

**Comment by prologic** [comment]
So are we going ahead with this patch? Do we have a test case yet?

**Comment by prologic** [comment]
bump @spaceone Can we close this or does this need further discussions/improvements? See: #85

**Comment by spaceone** [comment]
I have one more question:
currently if you ```yield seld.wait(x)``` (where x is a event instance) and `x` is fired after that yielding (in another handler of course) it is returned into the corouting after x is handled. Is this the wanted behavior? how can we wait for a event which does not exists (/was not fired) at that moment.
If x is never fired the coroutine is never continued. This is a design question as it is harder to debug errors then. Debugging would be easier if self.wait would raise a exception if the event does not exists. But maybe this is wanted behavior?

**Comment by prologic** [comment]
Can you show a simple code example?

**Comment by spaceone** [comment]
```
from circuits import *

class x(Event): pass

class Foo(BaseComponent):
    def init(self):
        self.x = x() 
        print 'init'

    @handler('started')
    def _on_started(self, m): 
        print 'started1'
        yield self.wait(self.x)
        print 'started2'

    @handler('signal', priority=1)
    def _on_signal(self, event, signo, stack):
        print 'signal', signo
        event.stop()
        self.fire(self.x)


f  = Foo()
f + Debugger()
f.run()
```

**Comment by prologic** [comment]
Ahh; and this doesn't currently work right? We're waiting for an event that hasn't yet been fired. I assume this is useful in some use-cases?

**Comment by spaceone** [comment]
Yes it works, but as I said, it makes debugging harder. So I am asking if it is the wanted behavior?

**Comment by spaceone** [comment]
It currently *does* work!

**Comment by prologic** [comment]
Firing an event created in some other place is hard to debug? Hmm I guess so :) another level of indirection!

I don't think we should remove this behaviour though as we'd be removing functionality for what reason?

**Comment by spaceone** [comment]
Do you understand the problem here? It is not a problem that it is fired somewhere else. It is a problem if the event is never fired because the programmer did a mistake.
Assume the example from above without the patch from the PR where i  ```yield self.wait(event)``` and the coroutine never continued because i missed to pass the `channels` A exception at that case would have prevented that i need to start the debugger.

**Comment by prologic** [comment]
Haha I can't make this example work in the sense that any signal kills the demo app :)

**Comment by spaceone** [comment]
use signal 15

**Comment by prologic** [comment]
Ahh I see; hmm yeah so you'd potentially be left with dead coroutines that will never complete?

**Comment by spaceone** [comment]
but you don't need that example, that's a working example. I am talking about 'broken' examples as which were the reason why i created the issue.

**Comment by spaceone** [comment]
yes, dead coroutines due to programming mistakes!

**Comment by prologic** [comment]
Hmm; question is how could you prevent this; let alone detect this?

Also somewhat related are preventing/detecting event loops/cycles. Event a fires Event b which in turn fires Event a

**Comment by spaceone** [comment]
For the first case you could lookup if there is an event x. But we can't do this as long as we support that event x can be fired after doing the wait().

The loops/cycles is a thing which occurred to me already. (It is very hard to kill the process then! KeyboardInterrupt does not help, kill -9 is needed). But I guess there are also valid use cases where one want to have this.

**Comment by prologic** [comment]
So are you saying we should remove ``self.wait()`` and just have ``self.call()`` which fires adn waits for the event in question?

**Comment by spaceone** [comment]
no!! wait is a very nice feature.

**Comment by prologic** [comment]
Okay :) Just making sure! Thing is I'm not sure even how to prevent this. We can't check for an event that doesn't exist as such; or are you saying that ``.wait()`` should check the event queue internally to see if the event it's being asked to wait for will actually ever occur?

OTOH; you do know there is a default timeout period right? and You *can* do: ``yield self.wait(x, timeout=10)`` for example.

**Comment by prologic** [comment]
I guess what I'm saying is (*now that I think about it and have had a coffee!*) it isn't really possible to have dead coroutines; they'll either terminate cleanly or timeout or error out.

**Comment by spaceone** [comment]
What is the default timeout? Is the timeout a value in seconds, milliseconds or how often .tick() is called?

**Comment by prologic** [comment]
Looks like the [default timeout](https://github.com/circuits/circuits/blob/master/circuits/core/manager.py#L502) is indefinite. Perhaps we *could* change this?

**Comment by spaceone** [comment]
No, let's not change the default timeout. This could lead to other errors. I think for now we can close the issue.

**Comment by prologic** [comment]
Okay :+1:  Great discussion!
