### ISSUE TITLE
Add an asynchronous equivalent to time.sleep()

### ISSUE THREAD

**Issue by prologic** [circuits/circuits#61]
Let's build a ``sleep()`` coroutine that pauses the execution of a coroutine for the given period of time.

We can trivially implement this I think :)

See: https://gist.github.com/prologic/f95e2fe451b5a8eccfa9

**Comment by prologic** [comment]
It'll likely *have* to be part of circuits's core internals because I think the design should be that yielding the ``sleep(x)`` coroutine causes the coroutine to be next iterated after x period of time.

**Comment by spaceone** [comment]
thanks very much!

**Comment by spaceone** [comment]
one can simple sleep_event.stop() from outside right?

**Comment by spaceone** [comment]
Look, I implemented this: https://github.com/spaceone/circuits.http/commit/fdfec3d653c7836b4beadd9ec16c8ed57e4d3391

**Comment by prologic** [comment]
Ahh very nice use of this :)

In terms of a ``Sleep.cancel()``; not sure how we would implement this. What are you thinking here?
