### ISSUE TITLE
Move project management of circuits to Github proper

### ISSUE THREAD

**Issue by prologic** [circuits/circuits#7]
See: https://bitbucket.org/circuits/circuits/issue/122/building-a-stronger-circuits-community

**Comment by y0no** [comment]
Maybe it will be great to change the github repo description who said that this one is just a mirror of the bitbucket's one.

**Comment by prologic** [comment]
@y0no Great idea! Thanks!

**Comment by prologic** [comment]
@y0no done :)

**Comment by y0no** [comment]
ah and maybe retrieve last version from bitbucket :D

**Comment by prologic** [comment]
@y0no we'll get to this shortly :)

**Comment by prologic** [comment]
I think this is done. #13 can be done independently of this.
