### ISSUE TITLE
MANIFEST.in -- Do we need one?

### ISSUE THREAD

**Issue by prologic** [circuits/circuits#78]
Do we need a [``MANIFEST.in``](https://github.com/circuits/circuits/blob/master/MANIFEST.in) file at all?

AFAIK this controls what "extra" files get packaged up in the source distributions.

I'm not sure that shipped distributions of circuits need to carry:

* [docs](https://github.com/circuits/circuits/tree/master/docs)
* [tests](https://github.com/circuits/circuits/tree/master/tests)
* [examples](https://github.com/circuits/circuits/tree/master/examples)

**Comment by eriol** [comment]
Hello, Debian maintainer of circuits here: just a point of view by downstream developers! :smile: 

If you ship tests I can run them during build time and configure our CI infrastructure to run them.
Honestly, I would like to have at least tests inside sdist to not have to test circuits manually.
I have noticed, however, that there are some tests that are failing ramdomly[¹] so enabling them at build time is a problem for Debian because it means package can not be built at all.

Currently documentation and examples are also shipped as a separated package.

[¹] https://travis-ci.org/circuits/circuits/builds

**Comment by eriol** [comment]
The good news is that several failures I'm seeing when running test in a clean Debian chroot are related to #54, so they will be fixed soon! Thanks!

**Comment by eriol** [comment]
Currently tests are being installed: we can simply ship them in sdist but not install them. @prologic what do you think about this? I can work on a PR if it's OK. Right now I simply remove tests, after running them, to not pollute namespace, creating Debian packages.

**Comment by eriol** [comment]
To reduce size of source dist, maybe the built documentation can be removed: this can enforced using the *prune* directive inside MANIFEST.in. For Debian this will be good, right now lintian (our package testing tool) is complaining about source missing for docs/build/html/_static/underscore.js and docs/build/html/_static/jquery.js.

**Comment by prologic** [comment]
@eriol Yeah if you could take this one up that would be awesome! Basically I just want to cleanup and strip down the sdist a bit. But if tests are useful for a packager's perspective then we'll leave them in!

**Comment by eriol** [comment]
@prologic sorry for the delay, see PR #108 for first results on shrinking source dist.

I have another question related to MANIFEST.in, can we ship manpages? For the Debian upload of circuits 3.1.0 I shipped them inside Debian packaging stuff, but I think other distributions can benefit from having man pages... and their size is paltry. :smile:

**Comment by prologic** [comment]
yes let's :)

On Tuesday, 21 July 2015, Daniele Tricoli <notifications@github.com> wrote:

> @prologic <https://github.com/prologic> sorry for the delay, see PR #108
> <https://github.com/circuits/circuits/pull/108> for first results on
> shrinking source dist.
>
> I have another question related to MANIFEST.in, can we ship manpages? For
> the Debian upload of circuits 3.1.0 I shipped them inside Debian packaging
> stuff, but I think other distributions can benefit from having man pages...
> and their size is paltry. [image: :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/circuits/circuits/issues/78#issuecomment-123129859>.
>


-- 

James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by eriol** [comment]
> yes let's :)

Done!

**Comment by prologic** [comment]
Okay closing this then as "resolved". Seems one is useful and we've managed to reduced the source dist quite considerably! Well done!
