### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by prologic** [circuits/circuits#8]
Update README to indicate we've moved the project management and source code of circuits to [Github](https://github.com/circuits]. Related: circuits/org#3 and #7

**Comment by mikus** [comment]
BTW what was the reason?

**Comment by prologic** [comment]
@mikus Time to move on :) Whilst the [Vote to move to Github](https://plus.google.com/+JamesMillsprologic/posts/EgjbE34Ndu1) was not represenative of the "whole" circuits community (*it's hard to get everyone on board!*) -- It was unanimous :)

**Comment by spaceone** [comment]
I did not vote due to "it was unanonymous" but for the simple reason that I don't want to register at google! ;)

**Comment by prologic** [comment]
@spaceone haha no worries! Sounds like we made the right decision anyway? :)

**Comment by spaceone** [comment]
It was the best decision we could make ;)

**Comment by prologic** [comment]
Awesome :)
