### ISSUE TITLE
Cleanup Code

### ISSUE THREAD

**Issue by prologic** [circuits/circuits#82]
* [ ] Run the codebase through ``autopep8``

There are several code modules that aren't PEP8 compliant and we are *meant* to be following the PEP8 style guide as part of ou "coding standards".

The [autopep8](https://pypi.python.org/pypi/autopep8) tool **will** pick up most (*if not all*) non-compliance.

**Comment by spaceone** [comment]
Let's also remove the "#Package: , #Date: ..., #Author: ..." header. It's untypically for python projects.

**Comment by spaceone** [comment]
Make sure to use "git diff -w" after autopep8 → in some scenarios it breaks code.

**Comment by prologic** [comment]
```
#!bash
$ tox
...
_____________________________________________ summary ______________________________________________
  docs: commands succeeded
  py26: commands succeeded
  py27: commands succeeded
  py32: commands succeeded
  py33: commands succeeded
  py34: commands succeeded
  pypy: commands succeeded
  congratulations :)
```

:)

**Comment by prologic** [comment]
Re header comments; done :)

**Comment by prologic** [comment]
Even with 65bb0c9:

```#!bash
$ time tox -r
_____________________________________________ summary ______________________________________________
  docs: commands succeeded
  py26: commands succeeded
  py27: commands succeeded
  py32: commands succeeded
  py33: commands succeeded
  py34: commands succeeded
  pypy: commands succeeded
  congratulations :)

real	15m7.833s
user	3m12.971s
sys	0m10.452s
```

**Comment by prologic** [comment]
So if there are no other objections; I'll merge this in:

**Comment by prologic** [comment]
I'll also run the codebase through [autoflake](https://pypi.python.org/pypi/autoflake)

**Comment by prologic** [comment]
Going forward (*if you haven't seen already*) [landscape](https://landscape.io) will *ensure* that we continue to maintain good code quality :)
