### ISSUE TITLE
Vulnerabiltiy in XMLRPC / JSONRPC

### ISSUE THREAD

**Issue by spaceone** [circuits/circuits#87]
A user simply is able to call every event in every channel.

*Start a server:*
```#!bash
python circuits/examples/web/jsonrpc.py &
```

*Kill the server:*
```#!bash
curl http://localhost:8000/ \
    -H 'Content-Type: application/json' \
    -d '{"params": {"signo": 15, "stack": null}, "id": "", "method": "*.signal"}'
```

**Comment by prologic** [comment]
@spaceone I *dare* say though that is is *almost* by design :) :laughing: 

However; I believe we should address this! Any ideas?

**Comment by spaceone** [comment]
Maybe whitelist for allowed events?

**Comment by spaceone** [comment]
Is there any real life example where it is used?

**Comment by prologic** [comment]
Yeah I've used the JSONRPC Dispatcher in https://github.com/prologic/autodock

In terms of fixing this though; perhaps we need to think about a redesign for JSONRPC/XMLRPC in general where it doesn't blindly translate RPC methods into events.

**Comment by prologic** [comment]
@spaceone What are your thoughts regarding these component(s)? I'm inclined to close this issue as "won't fix" because implementing secure RPC should be left as an exercise up to the user/developer. For example in [kdb](https://github.com/prologic/kdb)'s [kdb.plugins.rmessage](https://github.com/prologic/kdb/blob/master/kdb/plugins/rmessage.py) plugin it's not possbile to do what you suggested above:

```#!bash
$ curl -v -u admin http://kdb.vz1.bne.shortcircuit.net.au/jsonrpc -H 'Content-Type: application/json' -d '{"params": {"signo": 15, "stack": null}, "id": "", "method": "*.signal"}'
Enter host password for user 'admin':
*   Trying 2001:44b8:2101:6801::2...
* Connected to kdb.vz1.bne.shortcircuit.net.au (2001:44b8:2101:6801::2) port 80 (#0)
* Server auth using Basic with user 'admin'
> POST /jsonrpc HTTP/1.1
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.41.0
> Host: kdb.vz1.bne.shortcircuit.net.au
> Accept: */*
> Content-Type: application/json
> Content-Length: 72
> 
* upload completely sent off: 72 out of 72 bytes
< HTTP/1.1 404 Not Found
< date: Sat, 15 Aug 2015 02:21:56 GMT
< content-length: 624
< content-type: text/html; charset=utf-8
< connection: close
< server: circuits.web/dev
< 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
 <head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
  <title>404 Not Found</title>
  <style type="text/css">
   #powered_by {
    margin-top: 20px;
    border-top: 2px solid black;
    font-style: italic;
   }

   #traceback {
    color: red;
   }
  </style>
 </head>
 <body>
  <h1>Not Found</h1>
  
  <pre id="traceback"></pre>
  
<div id="powered_by">
    <span>Powered by <a href="http://circuitsweb.com/">circuits.web/dev</a></span>
</div>

 </body>
</html>
* Closing connection 0
```

**Comment by prologic** [comment]
Retracted last comment; I'm not sure how to solve this. @spaceone: thoughts?

**Comment by prologic** [comment]
@spaceone: Actually now that I think about the particular use-cases; I think we *should* just remove the ability to target "channels" via RPC and instead let the user/developer do this if they so desire in their own "dispatchers" that listen to "rpc" events. This would be the simplest way and most secure as incoming "rpc" payloads would only ever hit the component/channel you specify in ``JSONRPC("/path", "encoding", "rpcchannel")``.

**Comment by spaceone** [comment]
This looks way better. There is still no validation of the event name. Now everybody can fire arbitrary events into self.rpc_channel.

**Comment by spaceone** [comment]
We could prefix the event name with 'rpc.' or/and call a method which can be overridden which dies a mapping from method → event name.

**Comment by prologic** [comment]
I don't think we should do this; primarily because it completely breaks the API and the notion that you can loosely couple and cooperate with components that listen to events on the ``rpc_channel``. This would also completely break for example [kdb](https://github.com/prologic/kdb) and it's various plugins that listen to "rpc" events.

I believe the kind of "whitelist/blacklist" you're talking about *can* in fact be implemented by a user application (*which I could demo in this issue?*); otherwise let's close this and move on :)

**Comment by spaceone** [comment]
With the fix you can still call the init() method of Component-inherited classes.

**Comment by prologic** [comment]
That would be because of:

```#!python
from circuits import Component


class App(Component):

    def init(self):
        pass
```

I suspect if you ``@handler(None)`` it won't get exposed?
